#!/usr/bin/env python3
"""Generate layout assertions (size + field offsets) for every public struct,
from bindgen/build/ufbx_typed.json (per-arch layouts computed by ufbx_ir.py).

The emitted tests pin the Rust #[repr(C)] types to the exact C layout of ufbx.h,
which the 1:1 native port and the c-abi test shim both depend on.

Usage: PYTHONPATH=<repo>/bindgen python3 generate_layout_tests.py -i ufbx_typed.json -o layout.rs
"""
import argparse, json, os
import ufbx_ir as ir

RENAME_FIELDS = {"type": "type_", "fn": "fn_"}

def struct_rust_name(st):
    name = ir.to_pascal(st.short_name)
    return name

def parse_pub_fields(*rs_paths):
    """Map of struct name -> set of pub field names, parsed from Rust sources."""
    import re
    out = {}
    cur = None
    for path in rs_paths:
        with open(path, "rt") as f:
            for line in f:
                m = re.match(r"pub struct (\w+)", line)
                if m:
                    cur = m.group(1)
                    out.setdefault(cur, set())
                    continue
                if cur is not None:
                    if line.startswith("}"):
                        cur = None
                        continue
                    fm = re.match(r"\s+pub (r#)?(\w+):", line)
                    if fm:
                        out[cur].add(fm.group(2))
    return out

def main():
    p = argparse.ArgumentParser()
    p.add_argument("-i", required=True)
    p.add_argument("-o", required=True)
    p.add_argument("--src", nargs="+", required=True, help="Rust sources to scan for pub fields")
    argv = p.parse_args()
    pub_fields = parse_pub_fields(*argv.src)

    with open(argv.i, "rt") as f:
        file = ir.from_json(ir.File, json.load(f))

    lines = []
    lines.append("// GENERATED by rust/ufbx/bindgen/generate_layout_tests.py — do not edit.")
    lines.append("// Pins Rust #[repr(C)] layouts to the C layouts computed from ufbx.h by ufbx_ir.py.")
    lines.append("#![allow(deprecated)]")
    lines.append("// The pinned offsets are computed from ufbx.h with ufbx_real = double;")
    lines.append("// under real-is-float the C layouts differ (runner_float is that oracle).")
    lines.append('#![cfg(not(feature = "real-is-float"))]')
    lines.append("use std::mem::{size_of, offset_of};")
    lines.append("use ufbx::*;")
    lines.append("")
    lines.append('#[cfg(target_pointer_width = "64")] const ARCH: &str = "x64";')
    lines.append('#[cfg(target_pointer_width = "32")] const ARCH: &str = "x86";')
    lines.append("")

    n_structs = 0
    n_offsets = 0
    body = []
    for name, st in file.structs.items():
        if st.is_anonymous:
            continue
        # Input/callback/interface structs are emitted as Raw* on the Rust side
        # with extra _begin_zero/_end_zero fields — sizes differ; skip for now.
        if st.is_input:
            continue
        typ = file.types.get(name)
        if typ is None or typ.size is None:
            continue
        rust = struct_rust_name(st)
        if rust not in pub_fields and ("Raw" + rust) in pub_fields:
            rust = "Raw" + rust
        if rust not in pub_fields:
            continue  # no Rust-side struct of this name (skip, e.g. internal-only)
        sizes = typ.size
        body.append(f"    // {name}")
        body.append(f'    check_size::<{rust}>("{rust}", {sizes["x64"]}, {sizes["x86"]});')
        n_structs += 1
        seen = set()
        for fd in st.fields:
            if fd.private or not fd.name or fd.name in seen:
                continue
            seen.add(fd.name)
            fname = RENAME_FIELDS.get(fd.name, fd.name)
            if fname not in pub_fields[rust]:
                continue  # not a public field on the Rust side (hidden/renamed)
            off = fd.offset
            if off is None:
                continue
            body.append(f'    check_off(offset_of!({rust}, {fname}), "{rust}.{fname}", {off["x64"]}, {off["x86"]});')
            n_offsets += 1

    lines.append("fn check_size<T>(name: &str, x64: usize, x86: usize) {")
    lines.append('    let want = if ARCH == "x64" { x64 } else { x86 };')
    lines.append('    assert_eq!(size_of::<T>(), want, "size mismatch for {}", name);')
    lines.append("}")
    lines.append("fn check_off(got: usize, name: &str, x64: usize, x86: usize) {")
    lines.append('    let want = if ARCH == "x64" { x64 } else { x86 };')
    lines.append('    assert_eq!(got, want, "offset mismatch for {}", name);')
    lines.append("}")
    lines.append("")
    lines.append("#[test]")
    lines.append("fn struct_layouts_match_c() {")
    lines.extend(body)
    lines.append("}")

    with open(argv.o, "wt") as f:
        f.write("\n".join(lines) + "\n")
    print(f"emitted {n_structs} size checks, {n_offsets} offset checks -> {argv.o}")

if __name__ == "__main__":
    main()
