// GENERATED by rust/ufbx/bindgen/generate_layout_tests.py — do not edit.
// Pins Rust #[repr(C)] layouts to the C layouts computed from ufbx.h by ufbx_ir.py.
#![allow(deprecated)]
use std::mem::{offset_of, size_of};
use ufbx::*;

#[cfg(target_pointer_width = "64")]
const ARCH: &str = "x64";
#[cfg(target_pointer_width = "32")]
const ARCH: &str = "x86";

fn check_size<T>(name: &str, x64: usize, x86: usize) {
    let want = if ARCH == "x64" { x64 } else { x86 };
    assert_eq!(size_of::<T>(), want, "size mismatch for {}", name);
}
fn check_off(got: usize, name: &str, x64: usize, x86: usize) {
    let want = if ARCH == "x64" { x64 } else { x86 };
    assert_eq!(got, want, "offset mismatch for {}", name);
}

#[test]
fn struct_layouts_match_c() {
    // ufbx_string
    check_size::<String>("String", 16, 8);
    check_off(offset_of!(String, length), "String.length", 8, 4);
    // ufbx_blob
    check_size::<Blob>("Blob", 16, 8);
    check_off(offset_of!(Blob, size), "Blob.size", 8, 4);
    // ufbx_vec2
    check_size::<Vec2>("Vec2", 16, 16);
    // ufbx_vec3
    check_size::<Vec3>("Vec3", 24, 24);
    // ufbx_vec4
    check_size::<Vec4>("Vec4", 32, 32);
    // ufbx_quat
    check_size::<Quat>("Quat", 32, 32);
    // ufbx_transform
    check_size::<Transform>("Transform", 80, 80);
    check_off(
        offset_of!(Transform, translation),
        "Transform.translation",
        0,
        0,
    );
    check_off(
        offset_of!(Transform, rotation),
        "Transform.rotation",
        24,
        24,
    );
    check_off(offset_of!(Transform, scale), "Transform.scale", 56, 56);
    // ufbx_matrix
    check_size::<Matrix>("Matrix", 96, 96);
    // ufbx_void_list
    check_size::<VoidList>("VoidList", 16, 8);
    check_off(offset_of!(VoidList, data), "VoidList.data", 0, 0);
    check_off(offset_of!(VoidList, count), "VoidList.count", 8, 4);
    // ufbx_dom_value
    check_size::<DomValue>("DomValue", 56, 40);
    check_off(offset_of!(DomValue, type_), "DomValue.type_", 0, 0);
    check_off(offset_of!(DomValue, value_str), "DomValue.value_str", 8, 4);
    check_off(
        offset_of!(DomValue, value_blob),
        "DomValue.value_blob",
        24,
        12,
    );
    check_off(
        offset_of!(DomValue, value_int),
        "DomValue.value_int",
        40,
        24,
    );
    check_off(
        offset_of!(DomValue, value_float),
        "DomValue.value_float",
        48,
        32,
    );
    // ufbx_dom_node
    check_size::<DomNode>("DomNode", 48, 24);
    check_off(offset_of!(DomNode, name), "DomNode.name", 0, 0);
    check_off(offset_of!(DomNode, children), "DomNode.children", 16, 8);
    check_off(offset_of!(DomNode, values), "DomNode.values", 32, 16);
    // ufbx_prop
    check_size::<Prop>("Prop", 104, 80);
    check_off(offset_of!(Prop, name), "Prop.name", 0, 0);
    check_off(offset_of!(Prop, type_), "Prop.type_", 20, 12);
    check_off(offset_of!(Prop, flags), "Prop.flags", 24, 16);
    check_off(offset_of!(Prop, value_str), "Prop.value_str", 32, 20);
    check_off(offset_of!(Prop, value_blob), "Prop.value_blob", 48, 28);
    check_off(offset_of!(Prop, value_int), "Prop.value_int", 64, 40);
    // ufbx_props
    check_size::<Props>("Props", 32, 16);
    check_off(offset_of!(Props, props), "Props.props", 0, 0);
    check_off(offset_of!(Props, num_animated), "Props.num_animated", 16, 8);
    check_off(offset_of!(Props, defaults), "Props.defaults", 24, 12);
    // ufbx_connection
    check_size::<Connection>("Connection", 48, 24);
    check_off(offset_of!(Connection, src), "Connection.src", 0, 0);
    check_off(offset_of!(Connection, dst), "Connection.dst", 8, 4);
    check_off(
        offset_of!(Connection, src_prop),
        "Connection.src_prop",
        16,
        8,
    );
    check_off(
        offset_of!(Connection, dst_prop),
        "Connection.dst_prop",
        32,
        16,
    );
    // ufbx_element
    check_size::<Element>("Element", 128, 68);
    check_off(offset_of!(Element, name), "Element.name", 0, 0);
    check_off(offset_of!(Element, props), "Element.props", 16, 8);
    check_off(
        offset_of!(Element, element_id),
        "Element.element_id",
        48,
        24,
    );
    check_off(offset_of!(Element, typed_id), "Element.typed_id", 52, 28);
    check_off(offset_of!(Element, instances), "Element.instances", 56, 32);
    check_off(offset_of!(Element, type_), "Element.type_", 72, 40);
    check_off(
        offset_of!(Element, connections_src),
        "Element.connections_src",
        80,
        44,
    );
    check_off(
        offset_of!(Element, connections_dst),
        "Element.connections_dst",
        96,
        52,
    );
    check_off(offset_of!(Element, dom_node), "Element.dom_node", 112, 60);
    check_off(offset_of!(Element, scene), "Element.scene", 120, 64);
    // ufbx_unknown
    check_size::<Unknown>("Unknown", 176, 92);
    check_off(offset_of!(Unknown, type_), "Unknown.type_", 128, 68);
    check_off(
        offset_of!(Unknown, super_type),
        "Unknown.super_type",
        144,
        76,
    );
    check_off(offset_of!(Unknown, sub_type), "Unknown.sub_type", 160, 84);
    // ufbx_node
    check_size::<Node>("Node", 1104, 968);
    check_off(offset_of!(Node, parent), "Node.parent", 128, 68);
    check_off(offset_of!(Node, children), "Node.children", 136, 72);
    check_off(offset_of!(Node, mesh), "Node.mesh", 152, 80);
    check_off(offset_of!(Node, light), "Node.light", 160, 84);
    check_off(offset_of!(Node, camera), "Node.camera", 168, 88);
    check_off(offset_of!(Node, bone), "Node.bone", 176, 92);
    check_off(offset_of!(Node, attrib), "Node.attrib", 184, 96);
    check_off(
        offset_of!(Node, geometry_transform_helper),
        "Node.geometry_transform_helper",
        192,
        100,
    );
    check_off(
        offset_of!(Node, scale_helper),
        "Node.scale_helper",
        200,
        104,
    );
    check_off(offset_of!(Node, attrib_type), "Node.attrib_type", 208, 108);
    check_off(offset_of!(Node, all_attribs), "Node.all_attribs", 216, 112);
    check_off(
        offset_of!(Node, inherit_mode),
        "Node.inherit_mode",
        232,
        120,
    );
    check_off(
        offset_of!(Node, original_inherit_mode),
        "Node.original_inherit_mode",
        236,
        124,
    );
    check_off(
        offset_of!(Node, local_transform),
        "Node.local_transform",
        240,
        128,
    );
    check_off(
        offset_of!(Node, geometry_transform),
        "Node.geometry_transform",
        320,
        208,
    );
    check_off(
        offset_of!(Node, inherit_scale),
        "Node.inherit_scale",
        400,
        288,
    );
    check_off(
        offset_of!(Node, inherit_scale_node),
        "Node.inherit_scale_node",
        424,
        312,
    );
    check_off(
        offset_of!(Node, rotation_order),
        "Node.rotation_order",
        432,
        316,
    );
    check_off(
        offset_of!(Node, euler_rotation),
        "Node.euler_rotation",
        440,
        320,
    );
    check_off(
        offset_of!(Node, node_to_parent),
        "Node.node_to_parent",
        464,
        344,
    );
    check_off(
        offset_of!(Node, node_to_world),
        "Node.node_to_world",
        560,
        440,
    );
    check_off(
        offset_of!(Node, geometry_to_node),
        "Node.geometry_to_node",
        656,
        536,
    );
    check_off(
        offset_of!(Node, geometry_to_world),
        "Node.geometry_to_world",
        752,
        632,
    );
    check_off(
        offset_of!(Node, unscaled_node_to_world),
        "Node.unscaled_node_to_world",
        848,
        728,
    );
    check_off(
        offset_of!(Node, adjust_pre_translation),
        "Node.adjust_pre_translation",
        944,
        824,
    );
    check_off(
        offset_of!(Node, adjust_pre_rotation),
        "Node.adjust_pre_rotation",
        968,
        848,
    );
    check_off(
        offset_of!(Node, adjust_pre_scale),
        "Node.adjust_pre_scale",
        1000,
        880,
    );
    check_off(
        offset_of!(Node, adjust_post_rotation),
        "Node.adjust_post_rotation",
        1008,
        888,
    );
    check_off(
        offset_of!(Node, adjust_post_scale),
        "Node.adjust_post_scale",
        1040,
        920,
    );
    check_off(
        offset_of!(Node, adjust_translation_scale),
        "Node.adjust_translation_scale",
        1048,
        928,
    );
    check_off(
        offset_of!(Node, adjust_mirror_axis),
        "Node.adjust_mirror_axis",
        1056,
        936,
    );
    check_off(offset_of!(Node, materials), "Node.materials", 1064, 940);
    check_off(offset_of!(Node, bind_pose), "Node.bind_pose", 1080, 948);
    check_off(offset_of!(Node, visible), "Node.visible", 1088, 952);
    check_off(offset_of!(Node, is_root), "Node.is_root", 1089, 953);
    check_off(
        offset_of!(Node, has_geometry_transform),
        "Node.has_geometry_transform",
        1090,
        954,
    );
    check_off(
        offset_of!(Node, use_rotation_space),
        "Node.use_rotation_space",
        1091,
        955,
    );
    check_off(
        offset_of!(Node, has_adjust_transform),
        "Node.has_adjust_transform",
        1092,
        956,
    );
    check_off(
        offset_of!(Node, has_root_adjust_transform),
        "Node.has_root_adjust_transform",
        1093,
        957,
    );
    check_off(
        offset_of!(Node, is_geometry_transform_helper),
        "Node.is_geometry_transform_helper",
        1094,
        958,
    );
    check_off(
        offset_of!(Node, is_scale_helper),
        "Node.is_scale_helper",
        1095,
        959,
    );
    check_off(
        offset_of!(Node, is_scale_compensate_parent),
        "Node.is_scale_compensate_parent",
        1096,
        960,
    );
    check_off(offset_of!(Node, node_depth), "Node.node_depth", 1100, 964);
    // ufbx_vertex_attrib
    check_size::<VertexAttrib>("VertexAttrib", 72, 36);
    check_off(
        offset_of!(VertexAttrib, exists),
        "VertexAttrib.exists",
        0,
        0,
    );
    check_off(
        offset_of!(VertexAttrib, values),
        "VertexAttrib.values",
        8,
        4,
    );
    check_off(
        offset_of!(VertexAttrib, indices),
        "VertexAttrib.indices",
        24,
        12,
    );
    check_off(
        offset_of!(VertexAttrib, value_reals),
        "VertexAttrib.value_reals",
        40,
        20,
    );
    check_off(
        offset_of!(VertexAttrib, unique_per_vertex),
        "VertexAttrib.unique_per_vertex",
        48,
        24,
    );
    check_off(
        offset_of!(VertexAttrib, values_w),
        "VertexAttrib.values_w",
        56,
        28,
    );
    // ufbx_vertex_real
    check_size::<VertexReal>("VertexReal", 72, 36);
    check_off(offset_of!(VertexReal, exists), "VertexReal.exists", 0, 0);
    check_off(offset_of!(VertexReal, values), "VertexReal.values", 8, 4);
    check_off(
        offset_of!(VertexReal, indices),
        "VertexReal.indices",
        24,
        12,
    );
    check_off(
        offset_of!(VertexReal, value_reals),
        "VertexReal.value_reals",
        40,
        20,
    );
    check_off(
        offset_of!(VertexReal, unique_per_vertex),
        "VertexReal.unique_per_vertex",
        48,
        24,
    );
    check_off(
        offset_of!(VertexReal, values_w),
        "VertexReal.values_w",
        56,
        28,
    );
    // ufbx_vertex_vec2
    check_size::<VertexVec2>("VertexVec2", 72, 36);
    check_off(offset_of!(VertexVec2, exists), "VertexVec2.exists", 0, 0);
    check_off(offset_of!(VertexVec2, values), "VertexVec2.values", 8, 4);
    check_off(
        offset_of!(VertexVec2, indices),
        "VertexVec2.indices",
        24,
        12,
    );
    check_off(
        offset_of!(VertexVec2, value_reals),
        "VertexVec2.value_reals",
        40,
        20,
    );
    check_off(
        offset_of!(VertexVec2, unique_per_vertex),
        "VertexVec2.unique_per_vertex",
        48,
        24,
    );
    check_off(
        offset_of!(VertexVec2, values_w),
        "VertexVec2.values_w",
        56,
        28,
    );
    // ufbx_vertex_vec3
    check_size::<VertexVec3>("VertexVec3", 72, 36);
    check_off(offset_of!(VertexVec3, exists), "VertexVec3.exists", 0, 0);
    check_off(offset_of!(VertexVec3, values), "VertexVec3.values", 8, 4);
    check_off(
        offset_of!(VertexVec3, indices),
        "VertexVec3.indices",
        24,
        12,
    );
    check_off(
        offset_of!(VertexVec3, value_reals),
        "VertexVec3.value_reals",
        40,
        20,
    );
    check_off(
        offset_of!(VertexVec3, unique_per_vertex),
        "VertexVec3.unique_per_vertex",
        48,
        24,
    );
    check_off(
        offset_of!(VertexVec3, values_w),
        "VertexVec3.values_w",
        56,
        28,
    );
    // ufbx_vertex_vec4
    check_size::<VertexVec4>("VertexVec4", 72, 36);
    check_off(offset_of!(VertexVec4, exists), "VertexVec4.exists", 0, 0);
    check_off(offset_of!(VertexVec4, values), "VertexVec4.values", 8, 4);
    check_off(
        offset_of!(VertexVec4, indices),
        "VertexVec4.indices",
        24,
        12,
    );
    check_off(
        offset_of!(VertexVec4, value_reals),
        "VertexVec4.value_reals",
        40,
        20,
    );
    check_off(
        offset_of!(VertexVec4, unique_per_vertex),
        "VertexVec4.unique_per_vertex",
        48,
        24,
    );
    check_off(
        offset_of!(VertexVec4, values_w),
        "VertexVec4.values_w",
        56,
        28,
    );
    // ufbx_uv_set
    check_size::<UvSet>("UvSet", 240, 120);
    check_off(offset_of!(UvSet, name), "UvSet.name", 0, 0);
    check_off(offset_of!(UvSet, index), "UvSet.index", 16, 8);
    check_off(offset_of!(UvSet, vertex_uv), "UvSet.vertex_uv", 24, 12);
    check_off(
        offset_of!(UvSet, vertex_tangent),
        "UvSet.vertex_tangent",
        96,
        48,
    );
    check_off(
        offset_of!(UvSet, vertex_bitangent),
        "UvSet.vertex_bitangent",
        168,
        84,
    );
    // ufbx_color_set
    check_size::<ColorSet>("ColorSet", 96, 48);
    check_off(offset_of!(ColorSet, name), "ColorSet.name", 0, 0);
    check_off(offset_of!(ColorSet, index), "ColorSet.index", 16, 8);
    check_off(
        offset_of!(ColorSet, vertex_color),
        "ColorSet.vertex_color",
        24,
        12,
    );
    // ufbx_edge
    check_size::<Edge>("Edge", 8, 8);
    // ufbx_face
    check_size::<Face>("Face", 8, 8);
    check_off(offset_of!(Face, index_begin), "Face.index_begin", 0, 0);
    check_off(offset_of!(Face, num_indices), "Face.num_indices", 4, 4);
    // ufbx_mesh_part
    check_size::<MeshPart>("MeshPart", 64, 32);
    check_off(offset_of!(MeshPart, index), "MeshPart.index", 0, 0);
    check_off(offset_of!(MeshPart, num_faces), "MeshPart.num_faces", 8, 4);
    check_off(
        offset_of!(MeshPart, num_triangles),
        "MeshPart.num_triangles",
        16,
        8,
    );
    check_off(
        offset_of!(MeshPart, num_empty_faces),
        "MeshPart.num_empty_faces",
        24,
        12,
    );
    check_off(
        offset_of!(MeshPart, num_point_faces),
        "MeshPart.num_point_faces",
        32,
        16,
    );
    check_off(
        offset_of!(MeshPart, num_line_faces),
        "MeshPart.num_line_faces",
        40,
        20,
    );
    check_off(
        offset_of!(MeshPart, face_indices),
        "MeshPart.face_indices",
        48,
        24,
    );
    // ufbx_face_group
    check_size::<FaceGroup>("FaceGroup", 24, 12);
    check_off(offset_of!(FaceGroup, id), "FaceGroup.id", 0, 0);
    check_off(offset_of!(FaceGroup, name), "FaceGroup.name", 8, 4);
    // ufbx_subdivision_weight_range
    check_size::<SubdivisionWeightRange>("SubdivisionWeightRange", 8, 8);
    check_off(
        offset_of!(SubdivisionWeightRange, weight_begin),
        "SubdivisionWeightRange.weight_begin",
        0,
        0,
    );
    check_off(
        offset_of!(SubdivisionWeightRange, num_weights),
        "SubdivisionWeightRange.num_weights",
        4,
        4,
    );
    // ufbx_subdivision_weight
    check_size::<SubdivisionWeight>("SubdivisionWeight", 16, 16);
    check_off(
        offset_of!(SubdivisionWeight, weight),
        "SubdivisionWeight.weight",
        0,
        0,
    );
    check_off(
        offset_of!(SubdivisionWeight, index),
        "SubdivisionWeight.index",
        8,
        8,
    );
    // ufbx_subdivision_result
    check_size::<SubdivisionResult>("SubdivisionResult", 96, 48);
    check_off(
        offset_of!(SubdivisionResult, result_memory_used),
        "SubdivisionResult.result_memory_used",
        0,
        0,
    );
    check_off(
        offset_of!(SubdivisionResult, temp_memory_used),
        "SubdivisionResult.temp_memory_used",
        8,
        4,
    );
    check_off(
        offset_of!(SubdivisionResult, result_allocs),
        "SubdivisionResult.result_allocs",
        16,
        8,
    );
    check_off(
        offset_of!(SubdivisionResult, temp_allocs),
        "SubdivisionResult.temp_allocs",
        24,
        12,
    );
    check_off(
        offset_of!(SubdivisionResult, source_vertex_ranges),
        "SubdivisionResult.source_vertex_ranges",
        32,
        16,
    );
    check_off(
        offset_of!(SubdivisionResult, source_vertex_weights),
        "SubdivisionResult.source_vertex_weights",
        48,
        24,
    );
    check_off(
        offset_of!(SubdivisionResult, skin_cluster_ranges),
        "SubdivisionResult.skin_cluster_ranges",
        64,
        32,
    );
    check_off(
        offset_of!(SubdivisionResult, skin_cluster_weights),
        "SubdivisionResult.skin_cluster_weights",
        80,
        40,
    );
    // ufbx_mesh
    check_size::<Mesh>("Mesh", 1264, 648);
    check_off(offset_of!(Mesh, num_vertices), "Mesh.num_vertices", 128, 68);
    check_off(offset_of!(Mesh, num_indices), "Mesh.num_indices", 136, 72);
    check_off(offset_of!(Mesh, num_faces), "Mesh.num_faces", 144, 76);
    check_off(
        offset_of!(Mesh, num_triangles),
        "Mesh.num_triangles",
        152,
        80,
    );
    check_off(offset_of!(Mesh, num_edges), "Mesh.num_edges", 160, 84);
    check_off(
        offset_of!(Mesh, max_face_triangles),
        "Mesh.max_face_triangles",
        168,
        88,
    );
    check_off(
        offset_of!(Mesh, num_empty_faces),
        "Mesh.num_empty_faces",
        176,
        92,
    );
    check_off(
        offset_of!(Mesh, num_point_faces),
        "Mesh.num_point_faces",
        184,
        96,
    );
    check_off(
        offset_of!(Mesh, num_line_faces),
        "Mesh.num_line_faces",
        192,
        100,
    );
    check_off(offset_of!(Mesh, faces), "Mesh.faces", 200, 104);
    check_off(
        offset_of!(Mesh, face_smoothing),
        "Mesh.face_smoothing",
        216,
        112,
    );
    check_off(
        offset_of!(Mesh, face_material),
        "Mesh.face_material",
        232,
        120,
    );
    check_off(offset_of!(Mesh, face_group), "Mesh.face_group", 248, 128);
    check_off(offset_of!(Mesh, face_hole), "Mesh.face_hole", 264, 136);
    check_off(offset_of!(Mesh, edges), "Mesh.edges", 280, 144);
    check_off(
        offset_of!(Mesh, edge_smoothing),
        "Mesh.edge_smoothing",
        296,
        152,
    );
    check_off(offset_of!(Mesh, edge_crease), "Mesh.edge_crease", 312, 160);
    check_off(
        offset_of!(Mesh, edge_visibility),
        "Mesh.edge_visibility",
        328,
        168,
    );
    check_off(
        offset_of!(Mesh, vertex_indices),
        "Mesh.vertex_indices",
        344,
        176,
    );
    check_off(offset_of!(Mesh, vertices), "Mesh.vertices", 360, 184);
    check_off(
        offset_of!(Mesh, vertex_first_index),
        "Mesh.vertex_first_index",
        376,
        192,
    );
    check_off(
        offset_of!(Mesh, vertex_position),
        "Mesh.vertex_position",
        392,
        200,
    );
    check_off(
        offset_of!(Mesh, vertex_normal),
        "Mesh.vertex_normal",
        464,
        236,
    );
    check_off(offset_of!(Mesh, vertex_uv), "Mesh.vertex_uv", 536, 272);
    check_off(
        offset_of!(Mesh, vertex_tangent),
        "Mesh.vertex_tangent",
        608,
        308,
    );
    check_off(
        offset_of!(Mesh, vertex_bitangent),
        "Mesh.vertex_bitangent",
        680,
        344,
    );
    check_off(
        offset_of!(Mesh, vertex_color),
        "Mesh.vertex_color",
        752,
        380,
    );
    check_off(
        offset_of!(Mesh, vertex_crease),
        "Mesh.vertex_crease",
        824,
        416,
    );
    check_off(offset_of!(Mesh, uv_sets), "Mesh.uv_sets", 896, 452);
    check_off(offset_of!(Mesh, color_sets), "Mesh.color_sets", 912, 460);
    check_off(offset_of!(Mesh, materials), "Mesh.materials", 928, 468);
    check_off(offset_of!(Mesh, face_groups), "Mesh.face_groups", 944, 476);
    check_off(
        offset_of!(Mesh, material_parts),
        "Mesh.material_parts",
        960,
        484,
    );
    check_off(
        offset_of!(Mesh, face_group_parts),
        "Mesh.face_group_parts",
        976,
        492,
    );
    check_off(
        offset_of!(Mesh, material_part_usage_order),
        "Mesh.material_part_usage_order",
        992,
        500,
    );
    check_off(
        offset_of!(Mesh, skinned_is_local),
        "Mesh.skinned_is_local",
        1008,
        508,
    );
    check_off(
        offset_of!(Mesh, skinned_position),
        "Mesh.skinned_position",
        1016,
        512,
    );
    check_off(
        offset_of!(Mesh, skinned_normal),
        "Mesh.skinned_normal",
        1088,
        548,
    );
    check_off(
        offset_of!(Mesh, skin_deformers),
        "Mesh.skin_deformers",
        1160,
        584,
    );
    check_off(
        offset_of!(Mesh, blend_deformers),
        "Mesh.blend_deformers",
        1176,
        592,
    );
    check_off(
        offset_of!(Mesh, cache_deformers),
        "Mesh.cache_deformers",
        1192,
        600,
    );
    check_off(
        offset_of!(Mesh, all_deformers),
        "Mesh.all_deformers",
        1208,
        608,
    );
    check_off(
        offset_of!(Mesh, subdivision_preview_levels),
        "Mesh.subdivision_preview_levels",
        1224,
        616,
    );
    check_off(
        offset_of!(Mesh, subdivision_render_levels),
        "Mesh.subdivision_render_levels",
        1228,
        620,
    );
    check_off(
        offset_of!(Mesh, subdivision_display_mode),
        "Mesh.subdivision_display_mode",
        1232,
        624,
    );
    check_off(
        offset_of!(Mesh, subdivision_boundary),
        "Mesh.subdivision_boundary",
        1236,
        628,
    );
    check_off(
        offset_of!(Mesh, subdivision_uv_boundary),
        "Mesh.subdivision_uv_boundary",
        1240,
        632,
    );
    check_off(
        offset_of!(Mesh, reversed_winding),
        "Mesh.reversed_winding",
        1244,
        636,
    );
    check_off(
        offset_of!(Mesh, generated_normals),
        "Mesh.generated_normals",
        1245,
        637,
    );
    check_off(
        offset_of!(Mesh, subdivision_evaluated),
        "Mesh.subdivision_evaluated",
        1246,
        638,
    );
    check_off(
        offset_of!(Mesh, subdivision_result),
        "Mesh.subdivision_result",
        1248,
        640,
    );
    check_off(
        offset_of!(Mesh, from_tessellated_nurbs),
        "Mesh.from_tessellated_nurbs",
        1256,
        644,
    );
    // ufbx_light
    check_size::<Light>("Light", 224, 168);
    check_off(offset_of!(Light, color), "Light.color", 128, 72);
    check_off(offset_of!(Light, intensity), "Light.intensity", 152, 96);
    check_off(
        offset_of!(Light, local_direction),
        "Light.local_direction",
        160,
        104,
    );
    check_off(offset_of!(Light, type_), "Light.type_", 184, 128);
    check_off(offset_of!(Light, decay), "Light.decay", 188, 132);
    check_off(offset_of!(Light, area_shape), "Light.area_shape", 192, 136);
    check_off(
        offset_of!(Light, inner_angle),
        "Light.inner_angle",
        200,
        144,
    );
    check_off(
        offset_of!(Light, outer_angle),
        "Light.outer_angle",
        208,
        152,
    );
    check_off(offset_of!(Light, cast_light), "Light.cast_light", 216, 160);
    check_off(
        offset_of!(Light, cast_shadows),
        "Light.cast_shadows",
        217,
        161,
    );
    // ufbx_coordinate_axes
    check_size::<CoordinateAxes>("CoordinateAxes", 12, 12);
    check_off(
        offset_of!(CoordinateAxes, right),
        "CoordinateAxes.right",
        0,
        0,
    );
    check_off(offset_of!(CoordinateAxes, up), "CoordinateAxes.up", 4, 4);
    check_off(
        offset_of!(CoordinateAxes, front),
        "CoordinateAxes.front",
        8,
        8,
    );
    // ufbx_camera
    check_size::<Camera>("Camera", 328, 272);
    check_off(
        offset_of!(Camera, projection_mode),
        "Camera.projection_mode",
        128,
        68,
    );
    check_off(
        offset_of!(Camera, resolution_is_pixels),
        "Camera.resolution_is_pixels",
        132,
        72,
    );
    check_off(offset_of!(Camera, resolution), "Camera.resolution", 136, 80);
    check_off(
        offset_of!(Camera, field_of_view_deg),
        "Camera.field_of_view_deg",
        152,
        96,
    );
    check_off(
        offset_of!(Camera, field_of_view_tan),
        "Camera.field_of_view_tan",
        168,
        112,
    );
    check_off(
        offset_of!(Camera, orthographic_extent),
        "Camera.orthographic_extent",
        184,
        128,
    );
    check_off(
        offset_of!(Camera, orthographic_size),
        "Camera.orthographic_size",
        192,
        136,
    );
    check_off(
        offset_of!(Camera, projection_plane),
        "Camera.projection_plane",
        208,
        152,
    );
    check_off(
        offset_of!(Camera, aspect_ratio),
        "Camera.aspect_ratio",
        224,
        168,
    );
    check_off(
        offset_of!(Camera, near_plane),
        "Camera.near_plane",
        232,
        176,
    );
    check_off(offset_of!(Camera, far_plane), "Camera.far_plane", 240, 184);
    check_off(
        offset_of!(Camera, projection_axes),
        "Camera.projection_axes",
        248,
        192,
    );
    check_off(
        offset_of!(Camera, aspect_mode),
        "Camera.aspect_mode",
        260,
        204,
    );
    check_off(
        offset_of!(Camera, aperture_mode),
        "Camera.aperture_mode",
        264,
        208,
    );
    check_off(offset_of!(Camera, gate_fit), "Camera.gate_fit", 268, 212);
    check_off(
        offset_of!(Camera, aperture_format),
        "Camera.aperture_format",
        272,
        216,
    );
    check_off(
        offset_of!(Camera, focal_length_mm),
        "Camera.focal_length_mm",
        280,
        224,
    );
    check_off(
        offset_of!(Camera, film_size_inch),
        "Camera.film_size_inch",
        288,
        232,
    );
    check_off(
        offset_of!(Camera, aperture_size_inch),
        "Camera.aperture_size_inch",
        304,
        248,
    );
    check_off(
        offset_of!(Camera, squeeze_ratio),
        "Camera.squeeze_ratio",
        320,
        264,
    );
    // ufbx_bone
    check_size::<Bone>("Bone", 152, 96);
    check_off(offset_of!(Bone, radius), "Bone.radius", 128, 72);
    check_off(
        offset_of!(Bone, relative_length),
        "Bone.relative_length",
        136,
        80,
    );
    check_off(offset_of!(Bone, is_root), "Bone.is_root", 144, 88);
    // ufbx_empty
    check_size::<Empty>("Empty", 128, 68);
    // ufbx_line_segment
    check_size::<LineSegment>("LineSegment", 8, 8);
    check_off(
        offset_of!(LineSegment, index_begin),
        "LineSegment.index_begin",
        0,
        0,
    );
    check_off(
        offset_of!(LineSegment, num_indices),
        "LineSegment.num_indices",
        4,
        4,
    );
    // ufbx_line_curve
    check_size::<LineCurve>("LineCurve", 208, 128);
    check_off(offset_of!(LineCurve, color), "LineCurve.color", 128, 72);
    check_off(
        offset_of!(LineCurve, control_points),
        "LineCurve.control_points",
        152,
        96,
    );
    check_off(
        offset_of!(LineCurve, point_indices),
        "LineCurve.point_indices",
        168,
        104,
    );
    check_off(
        offset_of!(LineCurve, segments),
        "LineCurve.segments",
        184,
        112,
    );
    check_off(
        offset_of!(LineCurve, from_tessellated_nurbs),
        "LineCurve.from_tessellated_nurbs",
        200,
        120,
    );
    // ufbx_nurbs_basis
    check_size::<NurbsBasis>("NurbsBasis", 80, 56);
    check_off(offset_of!(NurbsBasis, order), "NurbsBasis.order", 0, 0);
    check_off(
        offset_of!(NurbsBasis, topology),
        "NurbsBasis.topology",
        4,
        4,
    );
    check_off(
        offset_of!(NurbsBasis, knot_vector),
        "NurbsBasis.knot_vector",
        8,
        8,
    );
    check_off(offset_of!(NurbsBasis, t_min), "NurbsBasis.t_min", 24, 16);
    check_off(offset_of!(NurbsBasis, t_max), "NurbsBasis.t_max", 32, 24);
    check_off(offset_of!(NurbsBasis, spans), "NurbsBasis.spans", 40, 32);
    check_off(offset_of!(NurbsBasis, is_2d), "NurbsBasis.is_2d", 56, 40);
    check_off(
        offset_of!(NurbsBasis, num_wrap_control_points),
        "NurbsBasis.num_wrap_control_points",
        64,
        44,
    );
    check_off(offset_of!(NurbsBasis, valid), "NurbsBasis.valid", 72, 48);
    // ufbx_nurbs_curve
    check_size::<NurbsCurve>("NurbsCurve", 224, 136);
    check_off(offset_of!(NurbsCurve, basis), "NurbsCurve.basis", 128, 72);
    check_off(
        offset_of!(NurbsCurve, control_points),
        "NurbsCurve.control_points",
        208,
        128,
    );
    // ufbx_nurbs_surface
    check_size::<NurbsSurface>("NurbsSurface", 344, 216);
    check_off(
        offset_of!(NurbsSurface, basis_u),
        "NurbsSurface.basis_u",
        128,
        72,
    );
    check_off(
        offset_of!(NurbsSurface, basis_v),
        "NurbsSurface.basis_v",
        208,
        128,
    );
    check_off(
        offset_of!(NurbsSurface, num_control_points_u),
        "NurbsSurface.num_control_points_u",
        288,
        184,
    );
    check_off(
        offset_of!(NurbsSurface, num_control_points_v),
        "NurbsSurface.num_control_points_v",
        296,
        188,
    );
    check_off(
        offset_of!(NurbsSurface, control_points),
        "NurbsSurface.control_points",
        304,
        192,
    );
    check_off(
        offset_of!(NurbsSurface, span_subdivision_u),
        "NurbsSurface.span_subdivision_u",
        320,
        200,
    );
    check_off(
        offset_of!(NurbsSurface, span_subdivision_v),
        "NurbsSurface.span_subdivision_v",
        324,
        204,
    );
    check_off(
        offset_of!(NurbsSurface, flip_normals),
        "NurbsSurface.flip_normals",
        328,
        208,
    );
    check_off(
        offset_of!(NurbsSurface, material),
        "NurbsSurface.material",
        336,
        212,
    );
    // ufbx_nurbs_trim_surface
    check_size::<NurbsTrimSurface>("NurbsTrimSurface", 128, 68);
    // ufbx_nurbs_trim_boundary
    check_size::<NurbsTrimBoundary>("NurbsTrimBoundary", 128, 68);
    // ufbx_procedural_geometry
    check_size::<ProceduralGeometry>("ProceduralGeometry", 128, 68);
    // ufbx_stereo_camera
    check_size::<StereoCamera>("StereoCamera", 144, 76);
    check_off(offset_of!(StereoCamera, left), "StereoCamera.left", 128, 68);
    check_off(
        offset_of!(StereoCamera, right),
        "StereoCamera.right",
        136,
        72,
    );
    // ufbx_camera_switcher
    check_size::<CameraSwitcher>("CameraSwitcher", 128, 68);
    // ufbx_marker
    check_size::<Marker>("Marker", 136, 72);
    check_off(offset_of!(Marker, type_), "Marker.type_", 128, 68);
    // ufbx_lod_level
    check_size::<LodLevel>("LodLevel", 16, 16);
    check_off(offset_of!(LodLevel, distance), "LodLevel.distance", 0, 0);
    check_off(offset_of!(LodLevel, display), "LodLevel.display", 8, 8);
    // ufbx_lod_group
    check_size::<LodGroup>("LodGroup", 176, 104);
    check_off(
        offset_of!(LodGroup, relative_distances),
        "LodGroup.relative_distances",
        128,
        68,
    );
    check_off(
        offset_of!(LodGroup, lod_levels),
        "LodGroup.lod_levels",
        136,
        72,
    );
    check_off(
        offset_of!(LodGroup, ignore_parent_transform),
        "LodGroup.ignore_parent_transform",
        152,
        80,
    );
    check_off(
        offset_of!(LodGroup, use_distance_limit),
        "LodGroup.use_distance_limit",
        153,
        81,
    );
    check_off(
        offset_of!(LodGroup, distance_limit_min),
        "LodGroup.distance_limit_min",
        160,
        88,
    );
    check_off(
        offset_of!(LodGroup, distance_limit_max),
        "LodGroup.distance_limit_max",
        168,
        96,
    );
    // ufbx_skin_vertex
    check_size::<SkinVertex>("SkinVertex", 16, 16);
    check_off(
        offset_of!(SkinVertex, weight_begin),
        "SkinVertex.weight_begin",
        0,
        0,
    );
    check_off(
        offset_of!(SkinVertex, num_weights),
        "SkinVertex.num_weights",
        4,
        4,
    );
    check_off(
        offset_of!(SkinVertex, dq_weight),
        "SkinVertex.dq_weight",
        8,
        8,
    );
    // ufbx_skin_weight
    check_size::<SkinWeight>("SkinWeight", 16, 16);
    check_off(
        offset_of!(SkinWeight, cluster_index),
        "SkinWeight.cluster_index",
        0,
        0,
    );
    check_off(offset_of!(SkinWeight, weight), "SkinWeight.weight", 8, 8);
    // ufbx_skin_deformer
    check_size::<SkinDeformer>("SkinDeformer", 232, 120);
    check_off(
        offset_of!(SkinDeformer, skinning_method),
        "SkinDeformer.skinning_method",
        128,
        68,
    );
    check_off(
        offset_of!(SkinDeformer, clusters),
        "SkinDeformer.clusters",
        136,
        72,
    );
    check_off(
        offset_of!(SkinDeformer, vertices),
        "SkinDeformer.vertices",
        152,
        80,
    );
    check_off(
        offset_of!(SkinDeformer, weights),
        "SkinDeformer.weights",
        168,
        88,
    );
    check_off(
        offset_of!(SkinDeformer, max_weights_per_vertex),
        "SkinDeformer.max_weights_per_vertex",
        184,
        96,
    );
    check_off(
        offset_of!(SkinDeformer, num_dq_weights),
        "SkinDeformer.num_dq_weights",
        192,
        100,
    );
    check_off(
        offset_of!(SkinDeformer, dq_vertices),
        "SkinDeformer.dq_vertices",
        200,
        104,
    );
    check_off(
        offset_of!(SkinDeformer, dq_weights),
        "SkinDeformer.dq_weights",
        216,
        112,
    );
    // ufbx_skin_cluster
    check_size::<SkinCluster>("SkinCluster", 640, 560);
    check_off(
        offset_of!(SkinCluster, bone_node),
        "SkinCluster.bone_node",
        128,
        68,
    );
    check_off(
        offset_of!(SkinCluster, geometry_to_bone),
        "SkinCluster.geometry_to_bone",
        136,
        72,
    );
    check_off(
        offset_of!(SkinCluster, mesh_node_to_bone),
        "SkinCluster.mesh_node_to_bone",
        232,
        168,
    );
    check_off(
        offset_of!(SkinCluster, bind_to_world),
        "SkinCluster.bind_to_world",
        328,
        264,
    );
    check_off(
        offset_of!(SkinCluster, geometry_to_world),
        "SkinCluster.geometry_to_world",
        424,
        360,
    );
    check_off(
        offset_of!(SkinCluster, geometry_to_world_transform),
        "SkinCluster.geometry_to_world_transform",
        520,
        456,
    );
    check_off(
        offset_of!(SkinCluster, num_weights),
        "SkinCluster.num_weights",
        600,
        536,
    );
    check_off(
        offset_of!(SkinCluster, vertices),
        "SkinCluster.vertices",
        608,
        540,
    );
    check_off(
        offset_of!(SkinCluster, weights),
        "SkinCluster.weights",
        624,
        548,
    );
    // ufbx_blend_deformer
    check_size::<BlendDeformer>("BlendDeformer", 144, 76);
    check_off(
        offset_of!(BlendDeformer, channels),
        "BlendDeformer.channels",
        128,
        68,
    );
    // ufbx_blend_keyframe
    check_size::<BlendKeyframe>("BlendKeyframe", 24, 24);
    check_off(
        offset_of!(BlendKeyframe, shape),
        "BlendKeyframe.shape",
        0,
        0,
    );
    check_off(
        offset_of!(BlendKeyframe, target_weight),
        "BlendKeyframe.target_weight",
        8,
        8,
    );
    check_off(
        offset_of!(BlendKeyframe, effective_weight),
        "BlendKeyframe.effective_weight",
        16,
        16,
    );
    // ufbx_blend_channel
    check_size::<BlendChannel>("BlendChannel", 160, 96);
    check_off(
        offset_of!(BlendChannel, weight),
        "BlendChannel.weight",
        128,
        72,
    );
    check_off(
        offset_of!(BlendChannel, keyframes),
        "BlendChannel.keyframes",
        136,
        80,
    );
    check_off(
        offset_of!(BlendChannel, target_shape),
        "BlendChannel.target_shape",
        152,
        88,
    );
    // ufbx_blend_shape
    check_size::<BlendShape>("BlendShape", 200, 104);
    check_off(
        offset_of!(BlendShape, num_offsets),
        "BlendShape.num_offsets",
        128,
        68,
    );
    check_off(
        offset_of!(BlendShape, offset_vertices),
        "BlendShape.offset_vertices",
        136,
        72,
    );
    check_off(
        offset_of!(BlendShape, position_offsets),
        "BlendShape.position_offsets",
        152,
        80,
    );
    check_off(
        offset_of!(BlendShape, normal_offsets),
        "BlendShape.normal_offsets",
        168,
        88,
    );
    check_off(
        offset_of!(BlendShape, offset_weights),
        "BlendShape.offset_weights",
        184,
        96,
    );
    // ufbx_cache_frame
    check_size::<CacheFrame>("CacheFrame", 88, 72);
    check_off(offset_of!(CacheFrame, channel), "CacheFrame.channel", 0, 0);
    check_off(offset_of!(CacheFrame, time), "CacheFrame.time", 16, 8);
    check_off(
        offset_of!(CacheFrame, filename),
        "CacheFrame.filename",
        24,
        16,
    );
    check_off(
        offset_of!(CacheFrame, file_format),
        "CacheFrame.file_format",
        40,
        24,
    );
    check_off(
        offset_of!(CacheFrame, mirror_axis),
        "CacheFrame.mirror_axis",
        44,
        28,
    );
    check_off(
        offset_of!(CacheFrame, scale_factor),
        "CacheFrame.scale_factor",
        48,
        32,
    );
    check_off(
        offset_of!(CacheFrame, data_format),
        "CacheFrame.data_format",
        56,
        40,
    );
    check_off(
        offset_of!(CacheFrame, data_encoding),
        "CacheFrame.data_encoding",
        60,
        44,
    );
    check_off(
        offset_of!(CacheFrame, data_offset),
        "CacheFrame.data_offset",
        64,
        48,
    );
    check_off(
        offset_of!(CacheFrame, data_count),
        "CacheFrame.data_count",
        72,
        56,
    );
    check_off(
        offset_of!(CacheFrame, data_element_bytes),
        "CacheFrame.data_element_bytes",
        76,
        60,
    );
    check_off(
        offset_of!(CacheFrame, data_total_bytes),
        "CacheFrame.data_total_bytes",
        80,
        64,
    );
    // ufbx_cache_channel
    check_size::<CacheChannel>("CacheChannel", 72, 40);
    check_off(offset_of!(CacheChannel, name), "CacheChannel.name", 0, 0);
    check_off(
        offset_of!(CacheChannel, interpretation),
        "CacheChannel.interpretation",
        16,
        8,
    );
    check_off(
        offset_of!(CacheChannel, interpretation_name),
        "CacheChannel.interpretation_name",
        24,
        12,
    );
    check_off(
        offset_of!(CacheChannel, frames),
        "CacheChannel.frames",
        40,
        20,
    );
    check_off(
        offset_of!(CacheChannel, mirror_axis),
        "CacheChannel.mirror_axis",
        56,
        28,
    );
    check_off(
        offset_of!(CacheChannel, scale_factor),
        "CacheChannel.scale_factor",
        64,
        32,
    );
    // ufbx_geometry_cache
    check_size::<GeometryCache>("GeometryCache", 64, 32);
    check_off(
        offset_of!(GeometryCache, root_filename),
        "GeometryCache.root_filename",
        0,
        0,
    );
    check_off(
        offset_of!(GeometryCache, channels),
        "GeometryCache.channels",
        16,
        8,
    );
    check_off(
        offset_of!(GeometryCache, frames),
        "GeometryCache.frames",
        32,
        16,
    );
    check_off(
        offset_of!(GeometryCache, extra_info),
        "GeometryCache.extra_info",
        48,
        24,
    );
    // ufbx_cache_deformer
    check_size::<CacheDeformer>("CacheDeformer", 168, 88);
    check_off(
        offset_of!(CacheDeformer, channel),
        "CacheDeformer.channel",
        128,
        68,
    );
    check_off(
        offset_of!(CacheDeformer, file),
        "CacheDeformer.file",
        144,
        76,
    );
    check_off(
        offset_of!(CacheDeformer, external_cache),
        "CacheDeformer.external_cache",
        152,
        80,
    );
    check_off(
        offset_of!(CacheDeformer, external_channel),
        "CacheDeformer.external_channel",
        160,
        84,
    );
    // ufbx_cache_file
    check_size::<CacheFile>("CacheFile", 240, 124);
    check_off(
        offset_of!(CacheFile, filename),
        "CacheFile.filename",
        128,
        68,
    );
    check_off(
        offset_of!(CacheFile, absolute_filename),
        "CacheFile.absolute_filename",
        144,
        76,
    );
    check_off(
        offset_of!(CacheFile, relative_filename),
        "CacheFile.relative_filename",
        160,
        84,
    );
    check_off(
        offset_of!(CacheFile, raw_filename),
        "CacheFile.raw_filename",
        176,
        92,
    );
    check_off(
        offset_of!(CacheFile, raw_absolute_filename),
        "CacheFile.raw_absolute_filename",
        192,
        100,
    );
    check_off(
        offset_of!(CacheFile, raw_relative_filename),
        "CacheFile.raw_relative_filename",
        208,
        108,
    );
    check_off(offset_of!(CacheFile, format), "CacheFile.format", 224, 116);
    check_off(
        offset_of!(CacheFile, external_cache),
        "CacheFile.external_cache",
        232,
        120,
    );
    // ufbx_material_map
    check_size::<MaterialMap>("MaterialMap", 56, 48);
    check_off(
        offset_of!(MaterialMap, value_int),
        "MaterialMap.value_int",
        32,
        32,
    );
    check_off(
        offset_of!(MaterialMap, texture),
        "MaterialMap.texture",
        40,
        40,
    );
    check_off(
        offset_of!(MaterialMap, has_value),
        "MaterialMap.has_value",
        48,
        44,
    );
    check_off(
        offset_of!(MaterialMap, texture_enabled),
        "MaterialMap.texture_enabled",
        49,
        45,
    );
    check_off(
        offset_of!(MaterialMap, feature_disabled),
        "MaterialMap.feature_disabled",
        50,
        46,
    );
    check_off(
        offset_of!(MaterialMap, value_components),
        "MaterialMap.value_components",
        51,
        47,
    );
    // ufbx_material_feature_info
    check_size::<MaterialFeatureInfo>("MaterialFeatureInfo", 2, 2);
    check_off(
        offset_of!(MaterialFeatureInfo, enabled),
        "MaterialFeatureInfo.enabled",
        0,
        0,
    );
    check_off(
        offset_of!(MaterialFeatureInfo, is_explicit),
        "MaterialFeatureInfo.is_explicit",
        1,
        1,
    );
    // ufbx_material_texture
    check_size::<MaterialTexture>("MaterialTexture", 40, 20);
    check_off(
        offset_of!(MaterialTexture, material_prop),
        "MaterialTexture.material_prop",
        0,
        0,
    );
    check_off(
        offset_of!(MaterialTexture, shader_prop),
        "MaterialTexture.shader_prop",
        16,
        8,
    );
    check_off(
        offset_of!(MaterialTexture, texture),
        "MaterialTexture.texture",
        32,
        16,
    );
    // ufbx_material_fbx_maps
    check_size::<MaterialFbxMaps>("MaterialFbxMaps", 1120, 960);
    // ufbx_material_pbr_maps
    check_size::<MaterialPbrMaps>("MaterialPbrMaps", 3136, 2688);
    // ufbx_material_features
    check_size::<MaterialFeatures>("MaterialFeatures", 46, 46);
    // ufbx_material
    check_size::<Material>("Material", 4496, 3800);
    check_off(offset_of!(Material, fbx), "Material.fbx", 128, 72);
    check_off(offset_of!(Material, pbr), "Material.pbr", 1248, 1032);
    check_off(
        offset_of!(Material, features),
        "Material.features",
        4384,
        3720,
    );
    check_off(
        offset_of!(Material, shader_type),
        "Material.shader_type",
        4432,
        3768,
    );
    check_off(offset_of!(Material, shader), "Material.shader", 4440, 3772);
    check_off(
        offset_of!(Material, shading_model_name),
        "Material.shading_model_name",
        4448,
        3776,
    );
    check_off(
        offset_of!(Material, shader_prop_prefix),
        "Material.shader_prop_prefix",
        4464,
        3784,
    );
    check_off(
        offset_of!(Material, textures),
        "Material.textures",
        4480,
        3792,
    );
    // ufbx_texture_layer
    check_size::<TextureLayer>("TextureLayer", 24, 16);
    check_off(
        offset_of!(TextureLayer, texture),
        "TextureLayer.texture",
        0,
        0,
    );
    check_off(
        offset_of!(TextureLayer, blend_mode),
        "TextureLayer.blend_mode",
        8,
        4,
    );
    check_off(offset_of!(TextureLayer, alpha), "TextureLayer.alpha", 16, 8);
    // ufbx_shader_texture_input
    check_size::<ShaderTextureInput>("ShaderTextureInput", 136, 96);
    check_off(
        offset_of!(ShaderTextureInput, name),
        "ShaderTextureInput.name",
        0,
        0,
    );
    check_off(
        offset_of!(ShaderTextureInput, value_int),
        "ShaderTextureInput.value_int",
        48,
        40,
    );
    check_off(
        offset_of!(ShaderTextureInput, value_str),
        "ShaderTextureInput.value_str",
        56,
        48,
    );
    check_off(
        offset_of!(ShaderTextureInput, value_blob),
        "ShaderTextureInput.value_blob",
        72,
        56,
    );
    check_off(
        offset_of!(ShaderTextureInput, texture),
        "ShaderTextureInput.texture",
        88,
        64,
    );
    check_off(
        offset_of!(ShaderTextureInput, texture_output_index),
        "ShaderTextureInput.texture_output_index",
        96,
        72,
    );
    check_off(
        offset_of!(ShaderTextureInput, texture_enabled),
        "ShaderTextureInput.texture_enabled",
        104,
        80,
    );
    check_off(
        offset_of!(ShaderTextureInput, prop),
        "ShaderTextureInput.prop",
        112,
        84,
    );
    check_off(
        offset_of!(ShaderTextureInput, texture_prop),
        "ShaderTextureInput.texture_prop",
        120,
        88,
    );
    check_off(
        offset_of!(ShaderTextureInput, texture_enabled_prop),
        "ShaderTextureInput.texture_enabled_prop",
        128,
        92,
    );
    // ufbx_shader_texture
    check_size::<ShaderTexture>("ShaderTexture", 112, 72);
    check_off(
        offset_of!(ShaderTexture, type_),
        "ShaderTexture.type_",
        0,
        0,
    );
    check_off(
        offset_of!(ShaderTexture, shader_name),
        "ShaderTexture.shader_name",
        8,
        4,
    );
    check_off(
        offset_of!(ShaderTexture, shader_type_id),
        "ShaderTexture.shader_type_id",
        24,
        16,
    );
    check_off(
        offset_of!(ShaderTexture, inputs),
        "ShaderTexture.inputs",
        32,
        24,
    );
    check_off(
        offset_of!(ShaderTexture, shader_source),
        "ShaderTexture.shader_source",
        48,
        32,
    );
    check_off(
        offset_of!(ShaderTexture, raw_shader_source),
        "ShaderTexture.raw_shader_source",
        64,
        40,
    );
    check_off(
        offset_of!(ShaderTexture, main_texture),
        "ShaderTexture.main_texture",
        80,
        48,
    );
    check_off(
        offset_of!(ShaderTexture, main_texture_output_index),
        "ShaderTexture.main_texture_output_index",
        88,
        56,
    );
    check_off(
        offset_of!(ShaderTexture, prop_prefix),
        "ShaderTexture.prop_prefix",
        96,
        64,
    );
    // ufbx_texture_file
    check_size::<TextureFile>("TextureFile", 120, 60);
    check_off(offset_of!(TextureFile, index), "TextureFile.index", 0, 0);
    check_off(
        offset_of!(TextureFile, filename),
        "TextureFile.filename",
        8,
        4,
    );
    check_off(
        offset_of!(TextureFile, absolute_filename),
        "TextureFile.absolute_filename",
        24,
        12,
    );
    check_off(
        offset_of!(TextureFile, relative_filename),
        "TextureFile.relative_filename",
        40,
        20,
    );
    check_off(
        offset_of!(TextureFile, raw_filename),
        "TextureFile.raw_filename",
        56,
        28,
    );
    check_off(
        offset_of!(TextureFile, raw_absolute_filename),
        "TextureFile.raw_absolute_filename",
        72,
        36,
    );
    check_off(
        offset_of!(TextureFile, raw_relative_filename),
        "TextureFile.raw_relative_filename",
        88,
        44,
    );
    check_off(
        offset_of!(TextureFile, content),
        "TextureFile.content",
        104,
        52,
    );
    // ufbx_texture
    check_size::<Texture>("Texture", 608, 456);
    check_off(offset_of!(Texture, type_), "Texture.type_", 128, 68);
    check_off(offset_of!(Texture, filename), "Texture.filename", 136, 72);
    check_off(
        offset_of!(Texture, absolute_filename),
        "Texture.absolute_filename",
        152,
        80,
    );
    check_off(
        offset_of!(Texture, relative_filename),
        "Texture.relative_filename",
        168,
        88,
    );
    check_off(
        offset_of!(Texture, raw_filename),
        "Texture.raw_filename",
        184,
        96,
    );
    check_off(
        offset_of!(Texture, raw_absolute_filename),
        "Texture.raw_absolute_filename",
        200,
        104,
    );
    check_off(
        offset_of!(Texture, raw_relative_filename),
        "Texture.raw_relative_filename",
        216,
        112,
    );
    check_off(offset_of!(Texture, content), "Texture.content", 232, 120);
    check_off(offset_of!(Texture, video), "Texture.video", 248, 128);
    check_off(
        offset_of!(Texture, file_index),
        "Texture.file_index",
        256,
        132,
    );
    check_off(offset_of!(Texture, has_file), "Texture.has_file", 260, 136);
    check_off(offset_of!(Texture, layers), "Texture.layers", 264, 140);
    check_off(offset_of!(Texture, shader), "Texture.shader", 280, 148);
    check_off(
        offset_of!(Texture, file_textures),
        "Texture.file_textures",
        288,
        152,
    );
    check_off(offset_of!(Texture, uv_set), "Texture.uv_set", 304, 160);
    check_off(offset_of!(Texture, wrap_u), "Texture.wrap_u", 320, 168);
    check_off(offset_of!(Texture, wrap_v), "Texture.wrap_v", 324, 172);
    check_off(
        offset_of!(Texture, has_uv_transform),
        "Texture.has_uv_transform",
        328,
        176,
    );
    check_off(
        offset_of!(Texture, uv_transform),
        "Texture.uv_transform",
        336,
        184,
    );
    check_off(
        offset_of!(Texture, texture_to_uv),
        "Texture.texture_to_uv",
        416,
        264,
    );
    check_off(
        offset_of!(Texture, uv_to_texture),
        "Texture.uv_to_texture",
        512,
        360,
    );
    // ufbx_video
    check_size::<Video>("Video", 240, 124);
    check_off(offset_of!(Video, filename), "Video.filename", 128, 68);
    check_off(
        offset_of!(Video, absolute_filename),
        "Video.absolute_filename",
        144,
        76,
    );
    check_off(
        offset_of!(Video, relative_filename),
        "Video.relative_filename",
        160,
        84,
    );
    check_off(
        offset_of!(Video, raw_filename),
        "Video.raw_filename",
        176,
        92,
    );
    check_off(
        offset_of!(Video, raw_absolute_filename),
        "Video.raw_absolute_filename",
        192,
        100,
    );
    check_off(
        offset_of!(Video, raw_relative_filename),
        "Video.raw_relative_filename",
        208,
        108,
    );
    check_off(offset_of!(Video, content), "Video.content", 224, 116);
    // ufbx_shader
    check_size::<Shader>("Shader", 152, 80);
    check_off(offset_of!(Shader, type_), "Shader.type_", 128, 68);
    check_off(offset_of!(Shader, bindings), "Shader.bindings", 136, 72);
    // ufbx_shader_prop_binding
    check_size::<ShaderPropBinding>("ShaderPropBinding", 32, 16);
    check_off(
        offset_of!(ShaderPropBinding, shader_prop),
        "ShaderPropBinding.shader_prop",
        0,
        0,
    );
    check_off(
        offset_of!(ShaderPropBinding, material_prop),
        "ShaderPropBinding.material_prop",
        16,
        8,
    );
    // ufbx_shader_binding
    check_size::<ShaderBinding>("ShaderBinding", 144, 76);
    check_off(
        offset_of!(ShaderBinding, prop_bindings),
        "ShaderBinding.prop_bindings",
        128,
        68,
    );
    // ufbx_prop_override
    check_size::<PropOverride>("PropOverride", 80, 64);
    check_off(
        offset_of!(PropOverride, element_id),
        "PropOverride.element_id",
        0,
        0,
    );
    check_off(
        offset_of!(PropOverride, prop_name),
        "PropOverride.prop_name",
        8,
        8,
    );
    check_off(
        offset_of!(PropOverride, value),
        "PropOverride.value",
        24,
        16,
    );
    check_off(
        offset_of!(PropOverride, value_str),
        "PropOverride.value_str",
        56,
        48,
    );
    check_off(
        offset_of!(PropOverride, value_int),
        "PropOverride.value_int",
        72,
        56,
    );
    // ufbx_transform_override
    check_size::<TransformOverride>("TransformOverride", 88, 88);
    check_off(
        offset_of!(TransformOverride, node_id),
        "TransformOverride.node_id",
        0,
        0,
    );
    check_off(
        offset_of!(TransformOverride, transform),
        "TransformOverride.transform",
        8,
        8,
    );
    // ufbx_anim
    check_size::<Anim>("Anim", 88, 56);
    check_off(offset_of!(Anim, time_begin), "Anim.time_begin", 0, 0);
    check_off(offset_of!(Anim, time_end), "Anim.time_end", 8, 8);
    check_off(offset_of!(Anim, layers), "Anim.layers", 16, 16);
    check_off(
        offset_of!(Anim, override_layer_weights),
        "Anim.override_layer_weights",
        32,
        24,
    );
    check_off(
        offset_of!(Anim, prop_overrides),
        "Anim.prop_overrides",
        48,
        32,
    );
    check_off(
        offset_of!(Anim, transform_overrides),
        "Anim.transform_overrides",
        64,
        40,
    );
    check_off(
        offset_of!(Anim, ignore_connections),
        "Anim.ignore_connections",
        80,
        48,
    );
    check_off(offset_of!(Anim, custom), "Anim.custom", 81, 49);
    // ufbx_anim_stack
    check_size::<AnimStack>("AnimStack", 168, 104);
    check_off(
        offset_of!(AnimStack, time_begin),
        "AnimStack.time_begin",
        128,
        72,
    );
    check_off(
        offset_of!(AnimStack, time_end),
        "AnimStack.time_end",
        136,
        80,
    );
    check_off(offset_of!(AnimStack, layers), "AnimStack.layers", 144, 88);
    check_off(offset_of!(AnimStack, anim), "AnimStack.anim", 160, 96);
    // ufbx_anim_prop
    check_size::<AnimProp>("AnimProp", 40, 20);
    check_off(offset_of!(AnimProp, element), "AnimProp.element", 0, 0);
    check_off(offset_of!(AnimProp, prop_name), "AnimProp.prop_name", 16, 8);
    check_off(
        offset_of!(AnimProp, anim_value),
        "AnimProp.anim_value",
        32,
        16,
    );
    // ufbx_anim_layer
    check_size::<AnimLayer>("AnimLayer", 208, 136);
    check_off(offset_of!(AnimLayer, weight), "AnimLayer.weight", 128, 72);
    check_off(
        offset_of!(AnimLayer, weight_is_animated),
        "AnimLayer.weight_is_animated",
        136,
        80,
    );
    check_off(offset_of!(AnimLayer, blended), "AnimLayer.blended", 137, 81);
    check_off(
        offset_of!(AnimLayer, additive),
        "AnimLayer.additive",
        138,
        82,
    );
    check_off(
        offset_of!(AnimLayer, compose_rotation),
        "AnimLayer.compose_rotation",
        139,
        83,
    );
    check_off(
        offset_of!(AnimLayer, compose_scale),
        "AnimLayer.compose_scale",
        140,
        84,
    );
    check_off(
        offset_of!(AnimLayer, anim_values),
        "AnimLayer.anim_values",
        144,
        88,
    );
    check_off(
        offset_of!(AnimLayer, anim_props),
        "AnimLayer.anim_props",
        160,
        96,
    );
    check_off(offset_of!(AnimLayer, anim), "AnimLayer.anim", 176, 104);
    // ufbx_anim_value
    check_size::<AnimValue>("AnimValue", 176, 112);
    check_off(
        offset_of!(AnimValue, default_value),
        "AnimValue.default_value",
        128,
        72,
    );
    check_off(offset_of!(AnimValue, curves), "AnimValue.curves", 152, 96);
    // ufbx_extrapolation
    check_size::<Extrapolation>("Extrapolation", 8, 8);
    check_off(offset_of!(Extrapolation, mode), "Extrapolation.mode", 0, 0);
    check_off(
        offset_of!(Extrapolation, repeat_count),
        "Extrapolation.repeat_count",
        4,
        4,
    );
    // ufbx_tangent
    check_size::<Tangent>("Tangent", 8, 8);
    check_off(offset_of!(Tangent, dx), "Tangent.dx", 0, 0);
    check_off(offset_of!(Tangent, dy), "Tangent.dy", 4, 4);
    // ufbx_keyframe
    check_size::<Keyframe>("Keyframe", 40, 40);
    check_off(offset_of!(Keyframe, time), "Keyframe.time", 0, 0);
    check_off(offset_of!(Keyframe, value), "Keyframe.value", 8, 8);
    check_off(
        offset_of!(Keyframe, interpolation),
        "Keyframe.interpolation",
        16,
        16,
    );
    check_off(offset_of!(Keyframe, left), "Keyframe.left", 20, 20);
    check_off(offset_of!(Keyframe, right), "Keyframe.right", 28, 28);
    // ufbx_anim_curve
    check_size::<AnimCurve>("AnimCurve", 192, 128);
    check_off(
        offset_of!(AnimCurve, keyframes),
        "AnimCurve.keyframes",
        128,
        68,
    );
    check_off(
        offset_of!(AnimCurve, pre_extrapolation),
        "AnimCurve.pre_extrapolation",
        144,
        76,
    );
    check_off(
        offset_of!(AnimCurve, post_extrapolation),
        "AnimCurve.post_extrapolation",
        152,
        84,
    );
    check_off(
        offset_of!(AnimCurve, min_value),
        "AnimCurve.min_value",
        160,
        96,
    );
    check_off(
        offset_of!(AnimCurve, max_value),
        "AnimCurve.max_value",
        168,
        104,
    );
    check_off(
        offset_of!(AnimCurve, min_time),
        "AnimCurve.min_time",
        176,
        112,
    );
    check_off(
        offset_of!(AnimCurve, max_time),
        "AnimCurve.max_time",
        184,
        120,
    );
    // ufbx_display_layer
    check_size::<DisplayLayer>("DisplayLayer", 176, 104);
    check_off(
        offset_of!(DisplayLayer, nodes),
        "DisplayLayer.nodes",
        128,
        68,
    );
    check_off(
        offset_of!(DisplayLayer, visible),
        "DisplayLayer.visible",
        144,
        76,
    );
    check_off(
        offset_of!(DisplayLayer, frozen),
        "DisplayLayer.frozen",
        145,
        77,
    );
    check_off(
        offset_of!(DisplayLayer, ui_color),
        "DisplayLayer.ui_color",
        152,
        80,
    );
    // ufbx_selection_set
    check_size::<SelectionSet>("SelectionSet", 144, 76);
    check_off(
        offset_of!(SelectionSet, nodes),
        "SelectionSet.nodes",
        128,
        68,
    );
    // ufbx_selection_node
    check_size::<SelectionNode>("SelectionNode", 200, 104);
    check_off(
        offset_of!(SelectionNode, target_node),
        "SelectionNode.target_node",
        128,
        68,
    );
    check_off(
        offset_of!(SelectionNode, target_mesh),
        "SelectionNode.target_mesh",
        136,
        72,
    );
    check_off(
        offset_of!(SelectionNode, include_node),
        "SelectionNode.include_node",
        144,
        76,
    );
    check_off(
        offset_of!(SelectionNode, vertices),
        "SelectionNode.vertices",
        152,
        80,
    );
    check_off(
        offset_of!(SelectionNode, edges),
        "SelectionNode.edges",
        168,
        88,
    );
    check_off(
        offset_of!(SelectionNode, faces),
        "SelectionNode.faces",
        184,
        96,
    );
    // ufbx_character
    check_size::<Character>("Character", 128, 68);
    // ufbx_constraint_target
    check_size::<ConstraintTarget>("ConstraintTarget", 96, 96);
    check_off(
        offset_of!(ConstraintTarget, node),
        "ConstraintTarget.node",
        0,
        0,
    );
    check_off(
        offset_of!(ConstraintTarget, weight),
        "ConstraintTarget.weight",
        8,
        8,
    );
    check_off(
        offset_of!(ConstraintTarget, transform),
        "ConstraintTarget.transform",
        16,
        16,
    );
    // ufbx_constraint
    check_size::<Constraint>("Constraint", 384, 288);
    check_off(offset_of!(Constraint, type_), "Constraint.type_", 128, 68);
    check_off(
        offset_of!(Constraint, type_name),
        "Constraint.type_name",
        136,
        72,
    );
    check_off(offset_of!(Constraint, node), "Constraint.node", 152, 80);
    check_off(
        offset_of!(Constraint, targets),
        "Constraint.targets",
        160,
        84,
    );
    check_off(offset_of!(Constraint, weight), "Constraint.weight", 176, 96);
    check_off(
        offset_of!(Constraint, active),
        "Constraint.active",
        184,
        104,
    );
    check_off(
        offset_of!(Constraint, constrain_translation),
        "Constraint.constrain_translation",
        185,
        105,
    );
    check_off(
        offset_of!(Constraint, constrain_rotation),
        "Constraint.constrain_rotation",
        188,
        108,
    );
    check_off(
        offset_of!(Constraint, constrain_scale),
        "Constraint.constrain_scale",
        191,
        111,
    );
    check_off(
        offset_of!(Constraint, transform_offset),
        "Constraint.transform_offset",
        200,
        120,
    );
    check_off(
        offset_of!(Constraint, aim_vector),
        "Constraint.aim_vector",
        280,
        200,
    );
    check_off(
        offset_of!(Constraint, aim_up_type),
        "Constraint.aim_up_type",
        304,
        224,
    );
    check_off(
        offset_of!(Constraint, aim_up_node),
        "Constraint.aim_up_node",
        312,
        228,
    );
    check_off(
        offset_of!(Constraint, aim_up_vector),
        "Constraint.aim_up_vector",
        320,
        232,
    );
    check_off(
        offset_of!(Constraint, ik_effector),
        "Constraint.ik_effector",
        344,
        256,
    );
    check_off(
        offset_of!(Constraint, ik_end_node),
        "Constraint.ik_end_node",
        352,
        260,
    );
    check_off(
        offset_of!(Constraint, ik_pole_vector),
        "Constraint.ik_pole_vector",
        360,
        264,
    );
    // ufbx_audio_layer
    check_size::<AudioLayer>("AudioLayer", 144, 76);
    check_off(offset_of!(AudioLayer, clips), "AudioLayer.clips", 128, 68);
    // ufbx_audio_clip
    check_size::<AudioClip>("AudioClip", 240, 124);
    check_off(
        offset_of!(AudioClip, filename),
        "AudioClip.filename",
        128,
        68,
    );
    check_off(
        offset_of!(AudioClip, absolute_filename),
        "AudioClip.absolute_filename",
        144,
        76,
    );
    check_off(
        offset_of!(AudioClip, relative_filename),
        "AudioClip.relative_filename",
        160,
        84,
    );
    check_off(
        offset_of!(AudioClip, raw_filename),
        "AudioClip.raw_filename",
        176,
        92,
    );
    check_off(
        offset_of!(AudioClip, raw_absolute_filename),
        "AudioClip.raw_absolute_filename",
        192,
        100,
    );
    check_off(
        offset_of!(AudioClip, raw_relative_filename),
        "AudioClip.raw_relative_filename",
        208,
        108,
    );
    check_off(
        offset_of!(AudioClip, content),
        "AudioClip.content",
        224,
        116,
    );
    // ufbx_bone_pose
    check_size::<BonePose>("BonePose", 200, 200);
    check_off(offset_of!(BonePose, bone_node), "BonePose.bone_node", 0, 0);
    check_off(
        offset_of!(BonePose, bone_to_world),
        "BonePose.bone_to_world",
        8,
        8,
    );
    check_off(
        offset_of!(BonePose, bone_to_parent),
        "BonePose.bone_to_parent",
        104,
        104,
    );
    // ufbx_pose
    check_size::<Pose>("Pose", 152, 80);
    check_off(offset_of!(Pose, is_bind_pose), "Pose.is_bind_pose", 128, 68);
    check_off(offset_of!(Pose, bone_poses), "Pose.bone_poses", 136, 72);
    // ufbx_metadata_object
    check_size::<MetadataObject>("MetadataObject", 128, 68);
    // ufbx_name_element
    check_size::<NameElement>("NameElement", 32, 20);
    check_off(offset_of!(NameElement, name), "NameElement.name", 0, 0);
    check_off(offset_of!(NameElement, type_), "NameElement.type_", 16, 8);
    check_off(
        offset_of!(NameElement, element),
        "NameElement.element",
        24,
        16,
    );
    // ufbx_application
    check_size::<Application>("Application", 48, 24);
    check_off(offset_of!(Application, vendor), "Application.vendor", 0, 0);
    check_off(offset_of!(Application, name), "Application.name", 16, 8);
    check_off(
        offset_of!(Application, version),
        "Application.version",
        32,
        16,
    );
    // ufbx_warning
    check_size::<Warning>("Warning", 40, 20);
    check_off(offset_of!(Warning, type_), "Warning.type_", 0, 0);
    check_off(
        offset_of!(Warning, description),
        "Warning.description",
        8,
        4,
    );
    check_off(
        offset_of!(Warning, element_id),
        "Warning.element_id",
        24,
        12,
    );
    check_off(offset_of!(Warning, count), "Warning.count", 32, 16);
    // ufbx_thumbnail
    check_size::<Thumbnail>("Thumbnail", 64, 36);
    check_off(offset_of!(Thumbnail, props), "Thumbnail.props", 0, 0);
    check_off(offset_of!(Thumbnail, width), "Thumbnail.width", 32, 16);
    check_off(offset_of!(Thumbnail, height), "Thumbnail.height", 36, 20);
    check_off(offset_of!(Thumbnail, format), "Thumbnail.format", 40, 24);
    check_off(offset_of!(Thumbnail, data), "Thumbnail.data", 48, 28);
    // ufbx_metadata
    check_size::<Metadata>("Metadata", 544, 352);
    check_off(offset_of!(Metadata, warnings), "Metadata.warnings", 0, 0);
    check_off(offset_of!(Metadata, ascii), "Metadata.ascii", 16, 8);
    check_off(offset_of!(Metadata, version), "Metadata.version", 20, 12);
    check_off(
        offset_of!(Metadata, file_format),
        "Metadata.file_format",
        24,
        16,
    );
    check_off(
        offset_of!(Metadata, may_contain_no_index),
        "Metadata.may_contain_no_index",
        28,
        20,
    );
    check_off(
        offset_of!(Metadata, may_contain_missing_vertex_position),
        "Metadata.may_contain_missing_vertex_position",
        29,
        21,
    );
    check_off(
        offset_of!(Metadata, may_contain_broken_elements),
        "Metadata.may_contain_broken_elements",
        30,
        22,
    );
    check_off(
        offset_of!(Metadata, is_unsafe),
        "Metadata.is_unsafe",
        31,
        23,
    );
    check_off(
        offset_of!(Metadata, has_warning),
        "Metadata.has_warning",
        32,
        24,
    );
    check_off(offset_of!(Metadata, creator), "Metadata.creator", 48, 40);
    check_off(
        offset_of!(Metadata, big_endian),
        "Metadata.big_endian",
        64,
        48,
    );
    check_off(offset_of!(Metadata, filename), "Metadata.filename", 72, 52);
    check_off(
        offset_of!(Metadata, relative_root),
        "Metadata.relative_root",
        88,
        60,
    );
    check_off(
        offset_of!(Metadata, raw_filename),
        "Metadata.raw_filename",
        104,
        68,
    );
    check_off(
        offset_of!(Metadata, raw_relative_root),
        "Metadata.raw_relative_root",
        120,
        76,
    );
    check_off(offset_of!(Metadata, exporter), "Metadata.exporter", 136, 84);
    check_off(
        offset_of!(Metadata, exporter_version),
        "Metadata.exporter_version",
        140,
        88,
    );
    check_off(
        offset_of!(Metadata, scene_props),
        "Metadata.scene_props",
        144,
        92,
    );
    check_off(
        offset_of!(Metadata, original_application),
        "Metadata.original_application",
        176,
        108,
    );
    check_off(
        offset_of!(Metadata, latest_application),
        "Metadata.latest_application",
        224,
        132,
    );
    check_off(
        offset_of!(Metadata, thumbnail),
        "Metadata.thumbnail",
        272,
        156,
    );
    check_off(
        offset_of!(Metadata, geometry_ignored),
        "Metadata.geometry_ignored",
        336,
        192,
    );
    check_off(
        offset_of!(Metadata, animation_ignored),
        "Metadata.animation_ignored",
        337,
        193,
    );
    check_off(
        offset_of!(Metadata, embedded_ignored),
        "Metadata.embedded_ignored",
        338,
        194,
    );
    check_off(
        offset_of!(Metadata, max_face_triangles),
        "Metadata.max_face_triangles",
        344,
        196,
    );
    check_off(
        offset_of!(Metadata, result_memory_used),
        "Metadata.result_memory_used",
        352,
        200,
    );
    check_off(
        offset_of!(Metadata, temp_memory_used),
        "Metadata.temp_memory_used",
        360,
        204,
    );
    check_off(
        offset_of!(Metadata, result_allocs),
        "Metadata.result_allocs",
        368,
        208,
    );
    check_off(
        offset_of!(Metadata, temp_allocs),
        "Metadata.temp_allocs",
        376,
        212,
    );
    check_off(
        offset_of!(Metadata, element_buffer_size),
        "Metadata.element_buffer_size",
        384,
        216,
    );
    check_off(
        offset_of!(Metadata, num_shader_textures),
        "Metadata.num_shader_textures",
        392,
        220,
    );
    check_off(
        offset_of!(Metadata, bone_prop_size_unit),
        "Metadata.bone_prop_size_unit",
        400,
        224,
    );
    check_off(
        offset_of!(Metadata, bone_prop_limb_length_relative),
        "Metadata.bone_prop_limb_length_relative",
        408,
        232,
    );
    check_off(
        offset_of!(Metadata, ortho_size_unit),
        "Metadata.ortho_size_unit",
        416,
        240,
    );
    check_off(
        offset_of!(Metadata, ktime_second),
        "Metadata.ktime_second",
        424,
        248,
    );
    check_off(
        offset_of!(Metadata, original_file_path),
        "Metadata.original_file_path",
        432,
        256,
    );
    check_off(
        offset_of!(Metadata, raw_original_file_path),
        "Metadata.raw_original_file_path",
        448,
        264,
    );
    check_off(
        offset_of!(Metadata, space_conversion),
        "Metadata.space_conversion",
        464,
        272,
    );
    check_off(
        offset_of!(Metadata, geometry_transform_handling),
        "Metadata.geometry_transform_handling",
        468,
        276,
    );
    check_off(
        offset_of!(Metadata, inherit_mode_handling),
        "Metadata.inherit_mode_handling",
        472,
        280,
    );
    check_off(
        offset_of!(Metadata, pivot_handling),
        "Metadata.pivot_handling",
        476,
        284,
    );
    check_off(
        offset_of!(Metadata, handedness_conversion_axis),
        "Metadata.handedness_conversion_axis",
        480,
        288,
    );
    check_off(
        offset_of!(Metadata, root_rotation),
        "Metadata.root_rotation",
        488,
        296,
    );
    check_off(
        offset_of!(Metadata, root_scale),
        "Metadata.root_scale",
        520,
        328,
    );
    check_off(
        offset_of!(Metadata, mirror_axis),
        "Metadata.mirror_axis",
        528,
        336,
    );
    check_off(
        offset_of!(Metadata, geometry_scale),
        "Metadata.geometry_scale",
        536,
        344,
    );
    // ufbx_scene_settings
    check_size::<SceneSettings>("SceneSettings", 128, 104);
    check_off(
        offset_of!(SceneSettings, props),
        "SceneSettings.props",
        0,
        0,
    );
    check_off(
        offset_of!(SceneSettings, axes),
        "SceneSettings.axes",
        32,
        16,
    );
    check_off(
        offset_of!(SceneSettings, unit_meters),
        "SceneSettings.unit_meters",
        48,
        32,
    );
    check_off(
        offset_of!(SceneSettings, frames_per_second),
        "SceneSettings.frames_per_second",
        56,
        40,
    );
    check_off(
        offset_of!(SceneSettings, ambient_color),
        "SceneSettings.ambient_color",
        64,
        48,
    );
    check_off(
        offset_of!(SceneSettings, default_camera),
        "SceneSettings.default_camera",
        88,
        72,
    );
    check_off(
        offset_of!(SceneSettings, time_mode),
        "SceneSettings.time_mode",
        104,
        80,
    );
    check_off(
        offset_of!(SceneSettings, time_protocol),
        "SceneSettings.time_protocol",
        108,
        84,
    );
    check_off(
        offset_of!(SceneSettings, snap_mode),
        "SceneSettings.snap_mode",
        112,
        88,
    );
    check_off(
        offset_of!(SceneSettings, original_axis_up),
        "SceneSettings.original_axis_up",
        116,
        92,
    );
    check_off(
        offset_of!(SceneSettings, original_unit_meters),
        "SceneSettings.original_unit_meters",
        120,
        96,
    );
    // ufbx_scene
    check_size::<Scene>("Scene", 1448, 848);
    check_off(offset_of!(Scene, metadata), "Scene.metadata", 0, 0);
    check_off(offset_of!(Scene, settings), "Scene.settings", 544, 352);
    check_off(offset_of!(Scene, root_node), "Scene.root_node", 672, 456);
    check_off(offset_of!(Scene, anim), "Scene.anim", 680, 460);
    check_off(
        offset_of!(Scene, texture_files),
        "Scene.texture_files",
        1360,
        800,
    );
    check_off(offset_of!(Scene, elements), "Scene.elements", 1376, 808);
    check_off(
        offset_of!(Scene, connections_src),
        "Scene.connections_src",
        1392,
        816,
    );
    check_off(
        offset_of!(Scene, connections_dst),
        "Scene.connections_dst",
        1408,
        824,
    );
    check_off(
        offset_of!(Scene, elements_by_name),
        "Scene.elements_by_name",
        1424,
        832,
    );
    check_off(offset_of!(Scene, dom_root), "Scene.dom_root", 1440, 840);
    // ufbx_curve_point
    check_size::<CurvePoint>("CurvePoint", 56, 56);
    check_off(offset_of!(CurvePoint, valid), "CurvePoint.valid", 0, 0);
    check_off(
        offset_of!(CurvePoint, position),
        "CurvePoint.position",
        8,
        8,
    );
    check_off(
        offset_of!(CurvePoint, derivative),
        "CurvePoint.derivative",
        32,
        32,
    );
    // ufbx_surface_point
    check_size::<SurfacePoint>("SurfacePoint", 80, 80);
    check_off(offset_of!(SurfacePoint, valid), "SurfacePoint.valid", 0, 0);
    check_off(
        offset_of!(SurfacePoint, position),
        "SurfacePoint.position",
        8,
        8,
    );
    check_off(
        offset_of!(SurfacePoint, derivative_u),
        "SurfacePoint.derivative_u",
        32,
        32,
    );
    check_off(
        offset_of!(SurfacePoint, derivative_v),
        "SurfacePoint.derivative_v",
        56,
        56,
    );
    // ufbx_topo_edge
    check_size::<TopoEdge>("TopoEdge", 28, 28);
    check_off(offset_of!(TopoEdge, index), "TopoEdge.index", 0, 0);
    check_off(offset_of!(TopoEdge, next), "TopoEdge.next", 4, 4);
    check_off(offset_of!(TopoEdge, prev), "TopoEdge.prev", 8, 8);
    check_off(offset_of!(TopoEdge, twin), "TopoEdge.twin", 12, 12);
    check_off(offset_of!(TopoEdge, face), "TopoEdge.face", 16, 16);
    check_off(offset_of!(TopoEdge, edge), "TopoEdge.edge", 20, 20);
    check_off(offset_of!(TopoEdge, flags), "TopoEdge.flags", 24, 24);
    // ufbx_vertex_stream
    check_size::<VertexStream>("VertexStream", 24, 12);
    // ufbx_allocator
    check_size::<RawAllocator>("RawAllocator", 40, 20);
    check_off(
        offset_of!(RawAllocator, alloc_fn),
        "RawAllocator.alloc_fn",
        0,
        0,
    );
    check_off(
        offset_of!(RawAllocator, realloc_fn),
        "RawAllocator.realloc_fn",
        8,
        4,
    );
    check_off(
        offset_of!(RawAllocator, free_fn),
        "RawAllocator.free_fn",
        16,
        8,
    );
    check_off(
        offset_of!(RawAllocator, free_allocator_fn),
        "RawAllocator.free_allocator_fn",
        24,
        12,
    );
    check_off(offset_of!(RawAllocator, user), "RawAllocator.user", 32, 16);
    // ufbx_stream
    check_size::<RawStream>("RawStream", 40, 20);
    check_off(offset_of!(RawStream, read_fn), "RawStream.read_fn", 0, 0);
    check_off(offset_of!(RawStream, skip_fn), "RawStream.skip_fn", 8, 4);
    check_off(offset_of!(RawStream, size_fn), "RawStream.size_fn", 16, 8);
    check_off(
        offset_of!(RawStream, close_fn),
        "RawStream.close_fn",
        24,
        12,
    );
    check_off(offset_of!(RawStream, user), "RawStream.user", 32, 16);
    // ufbx_open_file_info
    check_size::<OpenFileInfo>("OpenFileInfo", 32, 16);
    check_off(
        offset_of!(OpenFileInfo, context),
        "OpenFileInfo.context",
        0,
        0,
    );
    check_off(offset_of!(OpenFileInfo, type_), "OpenFileInfo.type_", 8, 4);
    check_off(
        offset_of!(OpenFileInfo, original_filename),
        "OpenFileInfo.original_filename",
        16,
        8,
    );
    // ufbx_open_file_cb
    check_size::<RawOpenFileCb>("RawOpenFileCb", 16, 8);
    check_off(offset_of!(RawOpenFileCb, fn_), "RawOpenFileCb.fn_", 0, 0);
    check_off(offset_of!(RawOpenFileCb, user), "RawOpenFileCb.user", 8, 4);
    // ufbx_close_memory_cb
    check_size::<RawCloseMemoryCb>("RawCloseMemoryCb", 16, 8);
    check_off(
        offset_of!(RawCloseMemoryCb, fn_),
        "RawCloseMemoryCb.fn_",
        0,
        0,
    );
    check_off(
        offset_of!(RawCloseMemoryCb, user),
        "RawCloseMemoryCb.user",
        8,
        4,
    );
    // ufbx_error_frame
    check_size::<ErrorFrame>("ErrorFrame", 40, 20);
    check_off(
        offset_of!(ErrorFrame, source_line),
        "ErrorFrame.source_line",
        0,
        0,
    );
    check_off(
        offset_of!(ErrorFrame, function),
        "ErrorFrame.function",
        8,
        4,
    );
    check_off(
        offset_of!(ErrorFrame, description),
        "ErrorFrame.description",
        24,
        12,
    );
    // ufbx_error
    check_size::<Error>("Error", 616, 436);
    check_off(offset_of!(Error, type_), "Error.type_", 0, 0);
    check_off(offset_of!(Error, description), "Error.description", 8, 4);
    check_off(offset_of!(Error, stack_size), "Error.stack_size", 24, 12);
    check_off(offset_of!(Error, stack), "Error.stack", 32, 16);
    // ufbx_progress
    check_size::<Progress>("Progress", 16, 16);
    check_off(
        offset_of!(Progress, bytes_read),
        "Progress.bytes_read",
        0,
        0,
    );
    check_off(
        offset_of!(Progress, bytes_total),
        "Progress.bytes_total",
        8,
        8,
    );
    // ufbx_progress_cb
    check_size::<RawProgressCb>("RawProgressCb", 16, 8);
    check_off(offset_of!(RawProgressCb, fn_), "RawProgressCb.fn_", 0, 0);
    check_off(offset_of!(RawProgressCb, user), "RawProgressCb.user", 8, 4);
    // ufbx_inflate_input
    check_size::<InflateInput>("InflateInput", 112, 72);
    check_off(
        offset_of!(InflateInput, total_size),
        "InflateInput.total_size",
        0,
        0,
    );
    check_off(offset_of!(InflateInput, data), "InflateInput.data", 8, 4);
    check_off(
        offset_of!(InflateInput, data_size),
        "InflateInput.data_size",
        16,
        8,
    );
    check_off(
        offset_of!(InflateInput, buffer),
        "InflateInput.buffer",
        24,
        12,
    );
    check_off(
        offset_of!(InflateInput, buffer_size),
        "InflateInput.buffer_size",
        32,
        16,
    );
    check_off(
        offset_of!(InflateInput, read_fn),
        "InflateInput.read_fn",
        40,
        20,
    );
    check_off(
        offset_of!(InflateInput, read_user),
        "InflateInput.read_user",
        48,
        24,
    );
    check_off(
        offset_of!(InflateInput, progress_cb),
        "InflateInput.progress_cb",
        56,
        28,
    );
    check_off(
        offset_of!(InflateInput, progress_interval_hint),
        "InflateInput.progress_interval_hint",
        72,
        40,
    );
    check_off(
        offset_of!(InflateInput, progress_size_before),
        "InflateInput.progress_size_before",
        80,
        48,
    );
    check_off(
        offset_of!(InflateInput, progress_size_after),
        "InflateInput.progress_size_after",
        88,
        56,
    );
    check_off(
        offset_of!(InflateInput, no_header),
        "InflateInput.no_header",
        96,
        64,
    );
    check_off(
        offset_of!(InflateInput, no_checksum),
        "InflateInput.no_checksum",
        97,
        65,
    );
    check_off(
        offset_of!(InflateInput, internal_fast_bits),
        "InflateInput.internal_fast_bits",
        104,
        68,
    );
    // ufbx_inflate_retain
    check_size::<InflateRetain>("InflateRetain", 8200, 8200);
    check_off(
        offset_of!(InflateRetain, initialized),
        "InflateRetain.initialized",
        0,
        0,
    );
    check_off(offset_of!(InflateRetain, data), "InflateRetain.data", 8, 8);
    // ufbx_baked_vec3
    check_size::<BakedVec3>("BakedVec3", 40, 40);
    check_off(offset_of!(BakedVec3, time), "BakedVec3.time", 0, 0);
    check_off(offset_of!(BakedVec3, value), "BakedVec3.value", 8, 8);
    check_off(offset_of!(BakedVec3, flags), "BakedVec3.flags", 32, 32);
    // ufbx_baked_quat
    check_size::<BakedQuat>("BakedQuat", 48, 48);
    check_off(offset_of!(BakedQuat, time), "BakedQuat.time", 0, 0);
    check_off(offset_of!(BakedQuat, value), "BakedQuat.value", 8, 8);
    check_off(offset_of!(BakedQuat, flags), "BakedQuat.flags", 40, 40);
    // ufbx_baked_node
    check_size::<BakedNode>("BakedNode", 64, 36);
    check_off(offset_of!(BakedNode, typed_id), "BakedNode.typed_id", 0, 0);
    check_off(
        offset_of!(BakedNode, element_id),
        "BakedNode.element_id",
        4,
        4,
    );
    check_off(
        offset_of!(BakedNode, constant_translation),
        "BakedNode.constant_translation",
        8,
        8,
    );
    check_off(
        offset_of!(BakedNode, constant_rotation),
        "BakedNode.constant_rotation",
        9,
        9,
    );
    check_off(
        offset_of!(BakedNode, constant_scale),
        "BakedNode.constant_scale",
        10,
        10,
    );
    check_off(
        offset_of!(BakedNode, translation_keys),
        "BakedNode.translation_keys",
        16,
        12,
    );
    check_off(
        offset_of!(BakedNode, rotation_keys),
        "BakedNode.rotation_keys",
        32,
        20,
    );
    check_off(
        offset_of!(BakedNode, scale_keys),
        "BakedNode.scale_keys",
        48,
        28,
    );
    // ufbx_baked_prop
    check_size::<BakedProp>("BakedProp", 40, 20);
    check_off(offset_of!(BakedProp, name), "BakedProp.name", 0, 0);
    check_off(
        offset_of!(BakedProp, constant_value),
        "BakedProp.constant_value",
        16,
        8,
    );
    check_off(offset_of!(BakedProp, keys), "BakedProp.keys", 24, 12);
    // ufbx_baked_element
    check_size::<BakedElement>("BakedElement", 24, 12);
    check_off(
        offset_of!(BakedElement, element_id),
        "BakedElement.element_id",
        0,
        0,
    );
    check_off(offset_of!(BakedElement, props), "BakedElement.props", 8, 4);
    // ufbx_baked_anim_metadata
    check_size::<BakedAnimMetadata>("BakedAnimMetadata", 32, 16);
    check_off(
        offset_of!(BakedAnimMetadata, result_memory_used),
        "BakedAnimMetadata.result_memory_used",
        0,
        0,
    );
    check_off(
        offset_of!(BakedAnimMetadata, temp_memory_used),
        "BakedAnimMetadata.temp_memory_used",
        8,
        4,
    );
    check_off(
        offset_of!(BakedAnimMetadata, result_allocs),
        "BakedAnimMetadata.result_allocs",
        16,
        8,
    );
    check_off(
        offset_of!(BakedAnimMetadata, temp_allocs),
        "BakedAnimMetadata.temp_allocs",
        24,
        12,
    );
    // ufbx_baked_anim
    check_size::<BakedAnim>("BakedAnim", 104, 72);
    check_off(offset_of!(BakedAnim, nodes), "BakedAnim.nodes", 0, 0);
    check_off(offset_of!(BakedAnim, elements), "BakedAnim.elements", 16, 8);
    check_off(
        offset_of!(BakedAnim, playback_time_begin),
        "BakedAnim.playback_time_begin",
        32,
        16,
    );
    check_off(
        offset_of!(BakedAnim, playback_time_end),
        "BakedAnim.playback_time_end",
        40,
        24,
    );
    check_off(
        offset_of!(BakedAnim, playback_duration),
        "BakedAnim.playback_duration",
        48,
        32,
    );
    check_off(
        offset_of!(BakedAnim, key_time_min),
        "BakedAnim.key_time_min",
        56,
        40,
    );
    check_off(
        offset_of!(BakedAnim, key_time_max),
        "BakedAnim.key_time_max",
        64,
        48,
    );
    check_off(
        offset_of!(BakedAnim, metadata),
        "BakedAnim.metadata",
        72,
        56,
    );
    // ufbx_thread_pool_info
    check_size::<ThreadPoolInfo>("ThreadPoolInfo", 4, 4);
    check_off(
        offset_of!(ThreadPoolInfo, max_concurrent_tasks),
        "ThreadPoolInfo.max_concurrent_tasks",
        0,
        0,
    );
    // ufbx_thread_pool
    check_size::<RawThreadPool>("RawThreadPool", 40, 20);
    check_off(
        offset_of!(RawThreadPool, init_fn),
        "RawThreadPool.init_fn",
        0,
        0,
    );
    check_off(
        offset_of!(RawThreadPool, run_fn),
        "RawThreadPool.run_fn",
        8,
        4,
    );
    check_off(
        offset_of!(RawThreadPool, wait_fn),
        "RawThreadPool.wait_fn",
        16,
        8,
    );
    check_off(
        offset_of!(RawThreadPool, free_fn),
        "RawThreadPool.free_fn",
        24,
        12,
    );
    check_off(
        offset_of!(RawThreadPool, user),
        "RawThreadPool.user",
        32,
        16,
    );
    // ufbx_panic
    check_size::<Panic>("Panic", 144, 136);
    check_off(offset_of!(Panic, did_panic), "Panic.did_panic", 0, 0);
}
