//! Port of the `// -- DEFLATE implementation` banner section, ufbx.c:1848-3279
//! (COMPLETE): lookup tables, the bit-stream reader (`ufbxi_bit_*` machinery),
//! Huffman tree construction (`ufbxi_huff_build_imp` / `ufbxi_huff_build`, the
//! `ufbxi_trees` overlay), static/dynamic tree init, `ufbxi_adler32`, the
//! slow/fast inflate block decoders, retain handling and the `ufbx_inflate`
//! entry point (C ABI shim in capi.rs).
//!
//! The whole C section is wrapped in `#if !defined(ufbx_inflate)`
//! (ufbx.c:1850): a compile-time override hook for substituting a custom
//! inflate implementation. The Rust port does not support that override, so
//! the guard collapses away (no cfg needed).
#![allow(dead_code, unused_macros, unused_imports)]
use core::ffi::c_void;
use core::mem::size_of;

use crate::generated::{InflateInput, InflateRetain, Progress, ProgressResult, RawProgressCb};
use crate::native::platform::{
    add_ptr, copy_16_bytes, is_aligned, max_sz, min_sz, read_u64, to_size, ufbx_assert,
    ufbxi_dev_assert, ufbxi_ignore, ufbxi_regression_assert, wrap_shr64, FastUint,
};
use crate::native::view::{view_read, view_write};

// C comment (ufbx.c:1852-1853):
// Lookup data: [0:5] extra bits [5:8] flags [16:32] base value
// Generated by `misc/deflate_lut.py`
// ufbx.c:1854-1859 `ufbxi_deflate_length_lut`
pub(crate) static DEFLATE_LENGTH_LUT: [u32; 32] = [
    0x00000020, 0x00030040, 0x00040040, 0x00050040, 0x00060040, 0x00070040, 0x00080040, 0x00090040,
    0x000a0040, 0x000b0041, 0x000d0041, 0x000f0041, 0x00110041, 0x00130042, 0x00170042, 0x001b0042,
    0x001f0042, 0x00230043, 0x002b0043, 0x00330043, 0x003b0043, 0x00430044, 0x00530044, 0x00630044,
    0x00730044, 0x00830045, 0x00a30045, 0x00c30045, 0x00e30045, 0x01020040, 0x00010020, 0x00010020,
];
// ufbx.c:1860-1865 `ufbxi_deflate_dist_lut`
pub(crate) static DEFLATE_DIST_LUT: [u32; 32] = [
    0x00010000, 0x00020000, 0x00030000, 0x00040000, 0x00050001, 0x00070001, 0x00090002, 0x000d0002,
    0x00110003, 0x00190003, 0x00210004, 0x00310004, 0x00410005, 0x00610005, 0x00810006, 0x00c10006,
    0x01010007, 0x01810007, 0x02010008, 0x03010008, 0x04010009, 0x06010009, 0x0801000a, 0x0c01000a,
    0x1001000b, 0x1801000b, 0x2001000c, 0x3001000c, 0x4001000d, 0x6001000d, 0x00010020, 0x00010020,
];

// ufbx.c:1867-1869 `ufbxi_deflate_code_length_permutation`
pub(crate) static DEFLATE_CODE_LENGTH_PERMUTATION: [u8; 19] = [
    16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15,
];

// ufbx.c:1871-1888 constants
pub(crate) const INFLATE_FAST_MIN_IN: usize = 8;
pub(crate) const INFLATE_FAST_MIN_OUT: usize = 2;

pub(crate) const HUFF_MAX_BITS: usize = 16;
pub(crate) const HUFF_MAX_VALUE: usize = 288;
pub(crate) const HUFF_FAST_BITS: u32 = 10;
pub(crate) const HUFF_FAST_SIZE: usize = 1 << HUFF_FAST_BITS;
pub(crate) const HUFF_FAST_MASK: usize = HUFF_FAST_SIZE - 1;
pub(crate) const HUFF_MAX_LONG_BITS: u32 = 5;
pub(crate) const HUFF_MAX_LONG_SYMS: usize = 380;

pub(crate) const HUFF_CODELEN_FAST_BITS: u32 = 8;
pub(crate) const HUFF_CODELEN_FAST_MASK: u32 = (1 << HUFF_CODELEN_FAST_BITS) - 1;

pub(crate) const HUFF_MAX_EXTRA_SYMS: usize = 32;

pub(crate) const HUFF_CODELEN_SYMS: usize = 19;
pub(crate) const HUFF_MAX_COMBINED_SYMS: usize = 320;

// ufbx.c:1890-1930 `ufbxi_bit_stream`
// NOTE: no `Clone`/`Copy` derive (trap #15 exception): `buffer`/`chunk_*` may
// point into `local_buffer`, so a bitwise copy would dangle; the C code never
// struct-assigns a `ufbxi_bit_stream` (verified — it is embedded by value in
// `ufbxi_deflate_context` and only ever passed by pointer).
#[repr(C)]
pub(crate) struct BitStream {
    // Number of bytes left to read from `read_fn()`
    pub input_left: usize,

    // User-supplied read callback
    pub read_fn: Option<unsafe extern "C" fn(*mut c_void, *mut c_void, usize) -> usize>,
    pub read_user: *mut c_void,

    // Buffer to read to from `read_fn()`, may point to `local_buffer` if user
    // didn't supply a suitable buffer.
    pub buffer: *mut u8,
    pub buffer_size: usize,

    // Current chunk of data to process, either the initial buffer of input
    // or part of `buffer`.
    pub chunk_begin: *const u8,    // < Begin of the buffer
    pub chunk_ptr: *const u8,      // < Next bytes to read to `bits`
    pub chunk_yield: *const u8,    // < End of data before needing to call `ufbxi_bit_yield()`
    pub chunk_end: *const u8,      // < End of data before needing to call `ufbxi_bit_refill()`
    pub chunk_real_end: *const u8, // < Actual end of the data buffer

    // Amount of bytes read before the current chunk
    pub num_read_before_chunk: usize,
    pub progress_bias: u64,
    pub progress_total: u64,
    pub progress_interval: usize,

    pub bits: u64,   // < Buffered bits
    pub left: usize, // < Number of valid low bits in `bits`

    // Progress tracking, maybe `NULL` it not requested
    pub progress_cb: RawProgressCb,

    // When `progress_cb.fn()` returns `false` set the `cancelled` flag and
    // set the buffered bits to `cancel_bits`.
    pub cancel_bits: u64,
    pub cancelled: bool,

    pub local_buffer: [u8; 256],
}

// Typed interior-mutable VIEW over the `stream` field (BitStream), reinterpreted in
// place. Sound despite the self-referential `buffer`→`local_buffer` pointer: a view is
// a typed lens over the same bytes at the same address — it never MOVES the struct, so
// the interior pointer stays valid, and `bit_stream_init` sets it up through the raw
// `s.get()` (`UnsafeCell` pointer, no retag). Single-threaded (deflate), POD leaves.
// Verified under Miri (SB + TB) on the DEFLATE-heavy load path. The hot-loop scalar
// leaves are exposed here; the `bit_*` machinery threads `&BitStreamView` whole.
pub(crate) type BitStreamView = crate::native::view::View<BitStream>;

impl BitStreamView {
    #[inline(always)]
    pub(crate) fn bits(&self) -> u64 {
        view_read!(self, bits)
    }
    #[inline(always)]
    pub(crate) fn set_bits(&self, bits: u64) {
        view_write!(self, bits, bits)
    }
    #[inline(always)]
    pub(crate) fn left(&self) -> usize {
        view_read!(self, left)
    }
    #[inline(always)]
    pub(crate) fn set_left(&self, left: usize) {
        view_write!(self, left, left)
    }
    #[inline(always)]
    pub(crate) fn chunk_ptr(&self) -> *const u8 {
        view_read!(self, chunk_ptr)
    }
    #[inline(always)]
    pub(crate) fn set_chunk_ptr(&self, chunk_ptr: *const u8) {
        view_write!(self, chunk_ptr, chunk_ptr)
    }
    #[inline(always)]
    pub(crate) fn chunk_yield(&self) -> *const u8 {
        view_read!(self, chunk_yield)
    }
    #[inline(always)]
    pub(crate) fn cancelled(&self) -> bool {
        view_read!(self, cancelled)
    }
}

// C comment (ufbx.c:1932-1980):
// Packed symbol information:
//
//   [0:5]   total_bits    // [fast=1] Number of bits in the symbol _including_ extra bits
//   [0:5]   extra_mask    // [fast=0] Mask of extra bits to use
//   [5]     end           // 1 if end/invalid symbol, always 0 if `fast` (*1)
//   [6]     match         // 1 if the symbol is a match length, always 0 in non `lit_length` trees (always 0 if `end`)
//   [7]     fast          // 1 if the symbol can be determined from the table bits and `end=0`
//   [8:16]  lit_byte      // [lit_length]                     Literal byte
//   [8:16]  len_index     // [lit_length, match=1]            Match length index
//   [8:16]  dist_index    // [dist]                           Match distance index
//   [8:16]  code_length   // [code_length]                    Dynamic Huffman code length code
//   [8:16]  long_offset   // [fast_sym, fast=0, extra_mask>0] Base offset (halved) to `long_sym[]`
//   [8:16]  code_prefix   // [fast_sym, fast=0, extra_mask=0] First 8-bits of the code (reverse of the lookup)
//
// (*1) Not allowing `end` if `fast` serves a dual purpose: It allows us to omit a check for the end symbol in the
// fast path and allows using the symbol as a 64-bit shift amount (x64/ARM64/WASM have native modulo 64 shifts).
//
// Valid bit patterns, all other patterns are forbidden (`sorted_to_sym[]` contains same patterns as `long_sym[]`):
//
//   tree                    b e m f v
//
//   lit_length.fast_sym[]   N 0 0 1 L  // Short N bit code (no extra allowed) for literal byte L
//   lit_length.fast_sym[]   N 0 1 1 I  // Short N bit code (huff+extra bits) for length index I
//   lit_length.fast_sym[]   M 0 0 0 X  // Long code at `lit_length.long_sym[X*2 + ((bits>>FAST_BITS) & M)]`
//   lit_length.fast_sym[]   0 0 0 0 R  // Extra long code with prefix R, use `lit_length.sorted_to_sym[]` to resolve (*1)
//   lit_length.fast_sym[]   N 1 0 0 0  // Short N bit code for end-of-block (256) symbol
//   lit_length.fast_sym[]   0 1 0 0 1  // Invalid lit_length code
//
//   lit_length.long_sym[]   N 0 0 0 L  // Long N bit code (no extra allowed) for literal byte L
//   lit_length.long_sym[]   N 0 1 0 I  // Long N bit code (huff+extra bits) for length index I
//   lit_length.long_sym[]   N 1 0 0 0  // Long N bit code for end-of-block (256) symbol
//   lit_length.long_sym[]   0 1 0 0 1  // Invalid lit_length code
//
//   dist.fast_sym[]         N 0 0 1 L  // Short N bit code (huff+extra bits) for distance index I
//   dist.fast_sym[]         M 0 0 0 X  // Long code at `dist.long_sym[X*2 + ((bits>>FAST_BITS) & M)]`
//   dist.fast_sym[]         0 0 0 0 R  // Extra long code with prefix R, use `dist.sorted_to_sym[]` to resolve (*1)
//   dist.fast_sym[]         N 1 0 0 1  // Unused symbol 30-31 or invalid distance code
//
//   dist.long_sym[]         N 0 0 0 I  // Long N bit code (huff+extra bits) for distance index I
//   dist.long_sym[]         N 1 0 0 1  // Unused symbol 30-31 or invalid distance code
//
//   code_length.fast_sym[]  N 0 0 1 B  // Short N bit code (huff only, extra handled explicitly) for symbol bit count B
//   code_length.fast_sym[]  M 0 0 0 X  // Long code at `dist.long_sym[X*2 + ((bits>>FAST_BITS) & M)]`
//   code_length.fast_sym[]  0 0 0 0 R  // Extra long code with prefix R, use `code_length.sorted_to_sym[]` to resolve (*1)
//
//   code_length.long_sym[]  N 0 0 0 B  // Long N bit code (huff only, extra handled explicitly) for symbol bit count B
//
// (*1) Never necessary if `fast_bits >= 10` due to `long_sym[]` covering all possible codes,
//
// ufbx.c:1981 `ufbxi_huff_sym`
pub(crate) type HuffSym = u16;

// ufbx.c:1983-1986 symbol accessor macros
#[inline(always)]
pub(crate) fn huff_sym_total_bits(sym: HuffSym) -> u32 {
    (sym as u32) & 0x1f
}
#[inline(always)]
pub(crate) fn huff_sym_long_mask(sym: HuffSym) -> u32 {
    (sym as u32) & 0x1f
}
#[inline(always)]
pub(crate) fn huff_sym_long_offset(sym: HuffSym) -> u32 {
    (sym as u32) >> 7u32
}
#[inline(always)]
pub(crate) fn huff_sym_value(sym: HuffSym) -> u32 {
    (sym as u32) >> 8u32
}

// ufbx.c:1988-1992
pub(crate) const HUFF_SYM_END: u32 = 0x20;
pub(crate) const HUFF_SYM_MATCH: u32 = 0x40;
pub(crate) const HUFF_SYM_FAST: u32 = 0x80;

// ufbx.c:1994 Error symbol, END (value 1)
pub(crate) const HUFF_ERROR_SYM: HuffSym = 0x0120;
// ufbx.c:1995 Uninitialized symbol for regression, END (value 2)
pub(crate) const HUFF_UNINITIALIZED_SYM: HuffSym = 0x0220;

// ufbx.c:1997-2010 `ufbxi_huff_tree`
#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct HuffTree {
    pub fast_sym: [HuffSym; HUFF_FAST_SIZE], // < Lookup from N bytes to symbol information
    pub long_sym: [HuffSym; HUFF_MAX_LONG_SYMS], // < Fast long symbol lookup
    pub sorted_to_sym: [HuffSym; HUFF_MAX_VALUE], // < Symbol information per sorted index

    pub extra_shift_base: [u32; HUFF_MAX_EXTRA_SYMS], // < [0:6] shift [16:32] base value
    pub extra_mask: [u16; HUFF_MAX_EXTRA_SYMS],       // < Mask for extra bits

    pub past_max_code: [u16; HUFF_MAX_BITS], // < One past maximum code value per bit length
    pub code_to_sorted: [i16; HUFF_MAX_BITS], // < Code to sorted symbol index per bit length
    pub num_symbols: u32,

    pub end_of_block_bits: u32,
}

// ufbx.c:2012-2021 `ufbxi_trees`
// C: anonymous union overlaying `struct { lit_length; dist; }` with
// `ufbxi_huff_tree trees[2]` — BOTH members are read. Ported as the real
// overlay (PORTING.md "Unions" table row 2012-2020): `[HuffTree; 2]` with
// named accessors for index 0 (`lit_length`) and index 1 (`dist`).
#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct Trees {
    pub trees: [HuffTree; 2],
    pub fast_bits: u32,
}

impl Trees {
    // union member `lit_length` == `trees[0]`
    #[inline(always)]
    pub(crate) fn lit_length(&self) -> &HuffTree {
        &self.trees[0]
    }
    #[inline(always)]
    pub(crate) fn lit_length_mut(&mut self) -> &mut HuffTree {
        &mut self.trees[0]
    }
    // union member `dist` == `trees[1]`
    #[inline(always)]
    pub(crate) fn dist(&self) -> &HuffTree {
        &self.trees[1]
    }
    #[inline(always)]
    pub(crate) fn dist_mut(&mut self) -> &mut HuffTree {
        &mut self.trees[1]
    }
}

// ufbx.c:2023-2026 `ufbxi_inflate_retain_imp`
#[repr(C)]
pub(crate) struct InflateRetainImp {
    pub initialized: bool,
    pub static_trees: Trees,
}

// ufbx.c:2028 `ufbx_static_assert(inflate_retain_size, ...)`
const _: () = assert!(size_of::<InflateRetainImp>() <= size_of::<InflateRetain>());

// ufbx.c:2030-2037 `ufbxi_deflate_context`
#[repr(C)]
pub(crate) struct InnerDeflateContext {
    pub stream: BitStream,
    pub fast_bits: u32,

    pub out_begin: *mut u8,
    pub out_ptr: *mut u8,
    pub out_end: *mut u8,
}

// Safe `&DeflateContext` handle over the fields-struct `InnerDeflateContext`,
// mirroring the `Context`/`InnerContext` seam in `parse.rs`. `MaybeUninit` because
// the embedded `BitStream` is self-referential (`buffer` points into
// `local_buffer`), so its transient state must never face a validity assertion;
// `UnsafeCell` gives the interior mutability every `&DeflateContext` site needs.
// Routing derefs through `.get()` keeps the raw-access discipline the
// self-referential fix restored (no `&mut *` reborrow of the stream).
#[repr(transparent)]
pub(crate) struct DeflateContext(
    core::cell::UnsafeCell<core::mem::MaybeUninit<InnerDeflateContext>>,
);

impl DeflateContext {
    #[inline(always)]
    pub(crate) fn get(&self) -> *mut InnerDeflateContext {
        self.0.get().cast()
    }

    // `stream` (BitStream) — typed VIEW handle (reinterpret-in-place); the anchored
    // root the `bit_*` machinery threads as `&BitStreamView`, and the source of the
    // hot-loop scalar leaves. The self-ref `buffer` pointer is set up through the
    // view's raw `s.get()` and survives the view's in-place retag (Miri-verified).
    #[inline(always)]
    pub(crate) fn stream_view(&self) -> &BitStreamView {
        unsafe { &*(&raw mut (*self.get()).stream as *mut BitStreamView) }
    }

    // `out_end` — scalar value accessor.
    #[inline(always)]
    pub(crate) fn out_end(&self) -> *mut u8 {
        view_read!(self, out_end)
    }

    #[inline(always)]
    pub(crate) fn set_out_end(&self, out_end: *mut u8) {
        view_write!(self, out_end, out_end)
    }

    // `out_ptr` — scalar value accessor.
    #[inline(always)]
    pub(crate) fn out_ptr(&self) -> *mut u8 {
        view_read!(self, out_ptr)
    }

    #[inline(always)]
    pub(crate) fn set_out_ptr(&self, out_ptr: *mut u8) {
        view_write!(self, out_ptr, out_ptr)
    }

    // `out_begin` — scalar value accessor.
    #[inline(always)]
    pub(crate) fn out_begin(&self) -> *mut u8 {
        view_read!(self, out_begin)
    }

    #[inline(always)]
    pub(crate) fn set_out_begin(&self, out_begin: *mut u8) {
        view_write!(self, out_begin, out_begin)
    }

    // `fast_bits` — scalar value accessor.
    #[inline(always)]
    pub(crate) fn fast_bits(&self) -> u32 {
        view_read!(self, fast_bits)
    }

    #[inline(always)]
    pub(crate) fn set_fast_bits(&self, fast_bits: u32) {
        view_write!(self, fast_bits, fast_bits)
    }
}

// ufbx.c:2039-2049 `ufbxi_bit_reverse`
#[inline(always)]
pub(crate) fn bit_reverse(mask: u32, num_bits: u32) -> u32 {
    ufbxi_dev_assert!(num_bits <= 16);
    let mut x = mask;
    x = ((x & 0xaaaa) >> 1) | ((x & 0x5555) << 1);
    x = ((x & 0xcccc) >> 2) | ((x & 0x3333) << 2);
    x = ((x & 0xf0f0) >> 4) | ((x & 0x0f0f) << 4);
    x = ((x & 0xff00) >> 8) | ((x & 0x00ff) << 8);
    x >> (16 - num_bits)
}

// ufbx.c:2051-2086 `ufbxi_bit_chunk_refill`
#[inline(never)]
pub(crate) unsafe fn bit_chunk_refill(s: &BitStreamView, ptr: *const u8) -> *const u8 {
    // `s.buffer` may point into `s.local_buffer` (see `bit_stream_init`), i.e.
    // the `BitStream` holds a raw pointer aliasing one of its own fields. `s` is
    // threaded as an interior-mutable `&BitStreamView`; field access goes
    // through the raw `s.get()` (an `UnsafeCell` pointer, no retag) so the
    // whole-struct — including `local_buffer`'s range — is never retagged and
    // that interior pointer stays valid, matching the C `s->field` access.
    // `ptr` is a plain byte position, not a borrow of the stream.

    // Copy any left-over data to the beginning of `buffer`
    // SAFETY: `chunk_real_end` and `ptr` are two positions in the one input
    // chunk `s` currently describes (`ptr <= chunk_real_end`), so they share an
    // object as `offset_from` requires; the field read goes through the live
    // `s.get()` pointer (see fn header).
    let mut left = to_size(unsafe { (*s.get()).chunk_real_end.offset_from(ptr) });
    ufbxi_dev_assert!(left < 64);
    if left > 0 {
        // C: memmove(s->buffer, ptr, left)
        // SAFETY: `left < 64 <= buffer_size`, so `s.buffer` has room for `left`
        // bytes and `ptr` addresses that many left-over readable bytes; `copy`
        // (memmove) tolerates the possible overlap.
        unsafe { core::ptr::copy(ptr, (*s.get()).buffer, left) };
    }

    // SAFETY: `ptr` and `chunk_begin` bracket the consumed span of the current
    // chunk (same object), so `offset_from` is in bounds; the field read/write
    // goes through the live `s.get()` pointer.
    unsafe {
        (*s.get()).num_read_before_chunk += to_size(ptr.offset_from((*s.get()).chunk_begin));
    }

    // Read more user data if the user supplied a `read_fn()`, otherwise
    // we assume the initial data chunk is the whole input buffer.
    // SAFETY: field reads through the live `s.get()` pointer (see fn header).
    if unsafe { (*s.get()).read_fn.is_some() && !(*s.get()).cancelled } {
        // SAFETY: field reads through the live `s.get()` pointer.
        let to_read = min_sz(
            unsafe { (*s.get()).input_left },
            unsafe { (*s.get()).buffer_size } - left,
        );
        if to_read > 0 {
            // SAFETY: `read_fn` is `Some` (checked above); calling it honours the
            // C read-callback contract with its paired `read_user`, and
            // `buffer.add(left)` stays within the `buffer_size`-byte buffer since
            // `to_read <= buffer_size - left`.
            let mut num_read = unsafe {
                ((*s.get()).read_fn.unwrap())(
                    (*s.get()).read_user,
                    (*s.get()).buffer.add(left) as *mut c_void,
                    to_read,
                )
            };
            // TODO: IO error, should unify with (currently broken) cancel logic
            if num_read > to_read {
                num_read = 0;
            }
            // SAFETY: field read through the live `s.get()` pointer.
            ufbxi_dev_assert!(unsafe { (*s.get()).input_left } >= num_read);
            // SAFETY: field read/write through the live `s.get()` pointer.
            unsafe {
                (*s.get()).input_left -= num_read;
            }
            left += num_read;
        }
    }

    // Pad the rest with zeros
    if left < 64 {
        // C: memset(s->buffer + left, 0, 64 - left)
        // SAFETY: `left < 64 <= buffer_size`, so `buffer + left` and the `64 -
        // left` bytes written stay within the buffer.
        unsafe { core::ptr::write_bytes((*s.get()).buffer.add(left), 0, 64 - left) };
        left = 64;
    }

    // SAFETY: field reads/writes through the live `s.get()` pointer;
    // `64 <= left <= buffer_size` here (padded up to 64, and the read capped at
    // `buffer_size - left`), so `buffer + (left - 8)` and `buffer + left` are
    // in-bounds one-past positions.
    unsafe {
        (*s.get()).chunk_begin = (*s.get()).buffer;
        (*s.get()).chunk_ptr = (*s.get()).buffer;
        (*s.get()).chunk_end = (*s.get()).buffer.add(left - 8);
        (*s.get()).chunk_real_end = (*s.get()).buffer.add(left);
        (*s.get()).buffer
    }
}

// ufbx.c:2088-2139 `ufbxi_bit_stream_init`
#[inline(never)]
pub(crate) unsafe fn bit_stream_init(s: &BitStreamView, input: *const InflateInput) {
    // `s.buffer` may point into `s.local_buffer` (set below), i.e. the
    // `BitStream` holds a raw pointer aliasing one of its own fields, so `s` is
    // an interior-mutable `&BitStreamView` and is derefed via the raw `s.get()`
    // (`UnsafeCell`, no retag) as `(*s.get()).field` to avoid a whole-struct
    // retag invalidating that interior pointer. `input` has no such aliasing and
    // is unconditionally dereferenced in the original C (never NULL), so a local
    // shared borrow is kept for it.
    // SAFETY: the original C dereferences `input` unconditionally (never NULL on
    // this path), so a shared borrow over it is sound.
    let input = unsafe { &*input };

    let mut data_size = input.data_size;
    if data_size > input.total_size {
        data_size = input.total_size;
    }

    // C: struct assignment `s->progress_cb = input->progress_cb` (memcpy);
    // `RawProgressCb` has no `Copy` derive in generated.rs — field-wise copy.
    // SAFETY: field writes through the live `s.get()` pointer (see fn header);
    // `add_ptr` offsets are within the caller's `data`/`data_size` window.
    unsafe {
        (*s.get()).read_fn = input.read_fn;
        (*s.get()).read_user = input.read_user;
        (*s.get()).progress_cb = RawProgressCb {
            fn_: input.progress_cb.fn_,
            user: input.progress_cb.user,
        };
        (*s.get()).chunk_begin = input.data as *const u8;
        (*s.get()).chunk_ptr = input.data as *const u8;
        (*s.get()).chunk_end =
            add_ptr(input.data as *mut u8, max_sz(8, data_size) - 8) as *const u8;
        (*s.get()).chunk_real_end = add_ptr(input.data as *mut u8, data_size) as *const u8;
        (*s.get()).input_left = input.total_size - data_size;
    }

    // Use the user buffer if it's large enough, otherwise `local_buffer`
    if input.buffer_size > size_of::<[u8; 256]>() {
        // SAFETY: field writes through the live `s.get()` pointer.
        unsafe {
            (*s.get()).buffer = input.buffer as *mut u8;
            (*s.get()).buffer_size = input.buffer_size;
        }
    } else {
        // SAFETY: field writes through the live `s.get()` pointer; `buffer` is
        // pointed at `s`'s own `local_buffer` field (the self-reference the fn
        // header describes).
        unsafe {
            (*s.get()).buffer = (*s.get()).local_buffer.as_mut_ptr();
            (*s.get()).buffer_size = size_of::<[u8; 256]>();
        }
    }
    // C: `input->total_size + input->progress_size_before + input->progress_size_after`
    // in uint64_t (wraps on overflow of user-supplied sizes).
    // SAFETY: field writes through the live `s.get()` pointer.
    unsafe {
        (*s.get()).num_read_before_chunk = 0;
        (*s.get()).progress_bias = input.progress_size_before;
        (*s.get()).progress_total = (input.total_size as u64)
            .wrapping_add(input.progress_size_before)
            .wrapping_add(input.progress_size_after);
    }
    // SAFETY: field read through the live `s.get()` pointer.
    if unsafe { (*s.get()).progress_cb.fn_.is_none() }
        || input.progress_interval_hint >= usize::MAX as u64
    {
        // SAFETY: field write through the live `s.get()` pointer.
        unsafe {
            (*s.get()).progress_interval = usize::MAX;
        }
    } else if input.progress_interval_hint > 0 {
        // SAFETY: field write through the live `s.get()` pointer.
        unsafe {
            (*s.get()).progress_interval = input.progress_interval_hint as usize;
        }
    } else {
        // SAFETY: field write through the live `s.get()` pointer.
        unsafe {
            (*s.get()).progress_interval = 0x4000;
        }
    }

    // Clear the initial bit buffer
    // SAFETY: field writes through the live `s.get()` pointer.
    unsafe {
        (*s.get()).cancelled = false;
        (*s.get()).bits = 0;
        (*s.get()).left = 0;
    }

    // If the initial data buffer is not large enough to be read directly
    // from refill the chunk once.
    if data_size < 64 {
        // SAFETY: `bit_chunk_refill` takes this same `&BitStreamView` and a
        // position pointer; `chunk_begin` is read through the live `s.get()`
        // pointer and points at the start of the current chunk.
        unsafe { bit_chunk_refill(s, (*s.get()).chunk_begin) };
    }

    // C-parity: `s->progress_interval + 8` wraps in size_t when
    // progress_interval == SIZE_MAX (progress_cb set + hint >= SIZE_MAX,
    // ufbx.c:2115-2116); the pointer `+` likewise wraps in practice.
    // SAFETY: field reads through the live `s.get()` pointer; `chunk_end` and
    // `chunk_ptr` are two positions in the same chunk, so `offset_from` is in
    // bounds.
    if unsafe {
        (*s.get()).progress_cb.fn_.is_some()
            && to_size((*s.get()).chunk_end.offset_from((*s.get()).chunk_ptr))
                > (*s.get()).progress_interval.wrapping_add(8)
    } {
        // SAFETY: field read/write through the live `s.get()` pointer.
        unsafe {
            (*s.get()).chunk_yield = (*s.get())
                .chunk_ptr
                .wrapping_add((*s.get()).progress_interval);
        }
    } else {
        // SAFETY: field read/write through the live `s.get()` pointer.
        unsafe {
            (*s.get()).chunk_yield = (*s.get()).chunk_end;
        }
    }
}

// ufbx.c:2141-2174 `ufbxi_bit_yield`
#[inline(never)]
pub(crate) unsafe fn bit_yield(s: &BitStreamView, ptr: *const u8) -> *const u8 {
    // `s.buffer` may point into `s.local_buffer` (see `bit_stream_init`), i.e.
    // the `BitStream` holds a raw pointer aliasing one of its own fields, so `s`
    // is an interior-mutable `&BitStreamView` derefed via the raw `s.get()`
    // (`UnsafeCell`, no retag) as `(*s.get()).field` to avoid a whole-struct
    // retag invalidating that interior pointer.

    let mut ptr = ptr;
    // SAFETY: `chunk_end` read through the live `s.get()` pointer (see fn header).
    if ptr > unsafe { (*s.get()).chunk_end } {
        // SAFETY: `bit_chunk_refill` takes this same `&BitStreamView` and the
        // current position `ptr`.
        ptr = unsafe { bit_chunk_refill(s, ptr) };
    }

    // SAFETY: `progress_cb.fn_` read through the live `s.get()` pointer.
    if unsafe { (*s.get()).progress_cb.fn_.is_some() } {
        // SAFETY: field reads through the live `s.get()` pointer; `ptr` and
        // `chunk_begin` are positions in the same chunk, so `offset_from` is in
        // bounds.
        let num_read = unsafe {
            (*s.get()).num_read_before_chunk + to_size(ptr.offset_from((*s.get()).chunk_begin))
        };

        // C: `ufbx_progress progress = { s->progress_bias + num_read, s->progress_total };`
        // SAFETY: `progress_bias`/`progress_total` read through the live
        // `s.get()` pointer.
        let progress = unsafe {
            Progress {
                bytes_read: (*s.get()).progress_bias.wrapping_add(num_read as u64),
                bytes_total: (*s.get()).progress_total,
            }
        };
        // C: `(uint32_t)s->progress_cb.fn(...)` — the raw fn type returns
        // RawEnum<ProgressResult> so a contract-violating callback is not UB.
        // SAFETY: `fn_` is `Some` (checked above); calling it honours the C
        // progress-callback contract with its paired `user`, and `&progress` is
        // a live local; the fields are read through the live `s.get()` pointer.
        let result = unsafe {
            ((*s.get()).progress_cb.fn_.unwrap())((*s.get()).progress_cb.user, &progress).as_raw()
        };
        ufbx_assert!(
            result == ProgressResult::Continue as u32 || result == ProgressResult::Cancel as u32
        );
        if result == ProgressResult::Cancel as u32 {
            // C: memset(s->local_buffer, 0, sizeof(s->local_buffer))
            // SAFETY: field reads/writes through the live `s.get()` pointer;
            // `ptr` is set to `local_buffer`'s start, so `ptr + (256 - 8)` and
            // `ptr + 256` stay within that 256-byte field, which is also the
            // `write_bytes` target and length.
            unsafe {
                (*s.get()).cancelled = true;
                ptr = (*s.get()).local_buffer.as_ptr();
                (*s.get()).buffer = (*s.get()).local_buffer.as_mut_ptr();
                (*s.get()).buffer_size = size_of::<[u8; 256]>();
                (*s.get()).chunk_begin = ptr;
                (*s.get()).chunk_ptr = ptr;
                (*s.get()).chunk_end = ptr.add(size_of::<[u8; 256]>() - 8);
                (*s.get()).chunk_real_end = ptr.add(size_of::<[u8; 256]>());
                core::ptr::write_bytes(
                    (*s.get()).local_buffer.as_mut_ptr(),
                    0,
                    size_of::<[u8; 256]>(),
                );
            }
        }
    }

    // C-parity: wrapping `+ 8` / pointer add for progress_interval == SIZE_MAX
    // (see `bit_stream_init`).
    // SAFETY: field reads through the live `s.get()` pointer; `chunk_end` and
    // `ptr` are positions in the same chunk, so `offset_from` is in bounds.
    if unsafe {
        (*s.get()).progress_cb.fn_.is_some()
            && to_size((*s.get()).chunk_end.offset_from(ptr))
                > (*s.get()).progress_interval.wrapping_add(8)
    } {
        // SAFETY: field read/write through the live `s.get()` pointer.
        unsafe {
            (*s.get()).chunk_yield = ptr.wrapping_add((*s.get()).progress_interval);
        }
    } else {
        // SAFETY: field read/write through the live `s.get()` pointer.
        unsafe {
            (*s.get()).chunk_yield = (*s.get()).chunk_end;
        }
    }

    ptr
}

// ufbx.c:2176-2194 `ufbxi_bit_refill`
#[inline(always)]
pub(crate) unsafe fn bit_refill(
    p_bits: &mut u64,
    p_left: &mut usize,
    p_data: &mut *const u8,
    s: &BitStreamView,
) {
    // `s.buffer` may point into `s.local_buffer` (see `bit_stream_init`), i.e.
    // the `BitStream` holds a raw pointer aliasing one of its own fields, so `s`
    // is an interior-mutable `&BitStreamView` derefed via the raw `s.get()`
    // (`UnsafeCell`, no retag) as `(*s.get()).field` to avoid a whole-struct
    // retag invalidating that interior pointer.

    // SAFETY: `chunk_yield` read through the live `s.get()` pointer (see fn header).
    if *p_data > unsafe { (*s.get()).chunk_yield } {
        // SAFETY: `bit_yield` takes this same `&BitStreamView` and the current
        // position `*p_data`.
        *p_data = unsafe { bit_yield(s, *p_data) };
        // SAFETY: `cancelled` read through the live `s.get()` pointer.
        if unsafe { (*s.get()).cancelled } {
            // Force an end-of-block symbol when cancelled so we don't need an
            // extra branch in the chunk decoding loop.
            // SAFETY: `cancel_bits` read through the live `s.get()` pointer.
            *p_bits = unsafe { (*s.get()).cancel_bits };
        }
    }

    // See https://fgiesen.wordpress.com/2018/02/20/reading-bits-in-far-too-many-ways-part-2/
    // variant 4. This branchless refill guarantees [56,63] bits to be valid in `*p_bits`.
    ufbxi_regression_assert!(*p_left <= 64);
    // SAFETY: `*p_data` addresses the current chunk position, which the refill
    // machinery keeps at least 8 bytes before `chunk_real_end`, so a 64-bit read
    // is in bounds.
    *p_bits |= unsafe { read_u64(crate::prelude::slice_from_ptr(*p_data, 8)) } << *p_left;
    // SAFETY: `(63 - *p_left) >> 3` is at most 7 bytes and the current chunk has
    // at least that much headroom before `chunk_real_end`.
    *p_data = unsafe { (*p_data).add((63 - *p_left) >> 3) };
    *p_left |= 56;
}

// ufbx.c:2196-2202 `ufbxi_macro_bit_refill_fast(m_bits, m_left, m_data, m_refill_bits)`
// See `ufbxi_bit_refill()`
macro_rules! macro_bit_refill_fast {
    ($m_bits:ident, $m_left:ident, $m_data:ident, $m_refill_bits:expr) => {{
        $crate::native::platform::ufbxi_regression_assert!($m_left <= 64);
        $m_bits |= $m_refill_bits << $m_left;
        $m_data = $m_data.add((63 - $m_left) >> 3);
        $m_left |= 56;
    }};
}
pub(crate) use macro_bit_refill_fast;

// ufbx.c:2204-2248 `ufbxi_bit_copy_bytes`
#[inline(never)]
pub(crate) unsafe fn bit_copy_bytes(dst: *mut c_void, s: &BitStreamView, len: usize) -> i32 {
    // `s.buffer` may point into `s.local_buffer` (see `bit_stream_init`), i.e.
    // the `BitStream` holds a raw pointer aliasing one of its own fields, so `s`
    // is an interior-mutable `&BitStreamView` derefed via the raw `s.get()`
    // (`UnsafeCell`, no retag) as `(*s.get()).field` to avoid a whole-struct
    // retag invalidating that interior pointer.

    // SAFETY: `left` read through the live `s.get()` pointer (see fn header).
    ufbx_assert!(unsafe { (*s.get()).left } % 8 == 0);
    let mut len = len;
    let mut ptr = dst as *mut u8;

    // Copy the buffered bits first
    // SAFETY: `left` read through the live `s.get()` pointer.
    while len > 0 && unsafe { (*s.get()).left } > 0 {
        // C: `*ptr++ = (char)(uint8_t)s->bits;`
        // SAFETY: this arm runs at most `len` times against the caller's
        // `len`-byte destination, so `*ptr` and the following `ptr + 1` stay in
        // bounds; `bits` read through the live `s.get()` pointer.
        unsafe {
            *ptr = (*s.get()).bits as u8;
            ptr = ptr.add(1);
        }
        len -= 1;
        // SAFETY: `bits`/`left` read-modify-write through the live `s.get()` pointer.
        unsafe {
            (*s.get()).bits >>= 8;
            (*s.get()).left -= 8;
        }
    }

    // Copied fully from buffer
    if len == 0 {
        return 1;
    }

    // We need to clear the top bits as there may be data
    // read ahead past `s->left` in some cases
    // SAFETY: `bits` write through the live `s.get()` pointer.
    unsafe {
        (*s.get()).bits = 0;
    }

    // Copy the current chunk
    // SAFETY: `chunk_real_end` and `chunk_ptr` are two positions in the same
    // chunk buffer, so `offset_from` is in bounds; reads through the live
    // `s.get()` pointer.
    let chunk_left =
        to_size(unsafe { (*s.get()).chunk_real_end.offset_from((*s.get()).chunk_ptr) });
    if chunk_left >= len {
        // C: memcpy(ptr, s->chunk_ptr, len)
        // SAFETY: `chunk_left >= len`, so `chunk_ptr` has `len` readable bytes
        // and `ptr` addresses the caller's remaining `len`-byte destination
        // (distinct objects); the advance stays within the chunk.
        unsafe {
            core::ptr::copy_nonoverlapping((*s.get()).chunk_ptr, ptr, len);
            (*s.get()).chunk_ptr = (*s.get()).chunk_ptr.add(len);
        }
        return 1;
    } else {
        // SAFETY: `chunk_left < len`, so `chunk_ptr` has `chunk_left` readable
        // bytes copied to the destination; `chunk_ptr` is advanced to its end
        // and `ptr` past the bytes just written (both in bounds).
        unsafe {
            core::ptr::copy_nonoverlapping((*s.get()).chunk_ptr, ptr, chunk_left);
            (*s.get()).chunk_ptr = (*s.get()).chunk_ptr.add(chunk_left);
            ptr = ptr.add(chunk_left);
        }
        len -= chunk_left;
    }

    // Read extra bytes from user
    // SAFETY: `input_left` read through the live `s.get()` pointer.
    if len > unsafe { (*s.get()).input_left } {
        return 0;
    }
    let mut num_read = 0usize;
    // SAFETY: `read_fn` read through the live `s.get()` pointer.
    if unsafe { (*s.get()).read_fn.is_some() } {
        // C-parity: no clamp on `num_read` here (unlike ufbxi_bit_chunk_refill,
        // ufbx.c:2068); a misbehaving read_fn wraps `input_left` in size_t and
        // the function returns 0 below.
        // SAFETY: `read_fn` is `Some` (checked above); calling it honours the C
        // read-callback contract with its paired `read_user`, and `ptr`/`len`
        // are the unconsumed tail of the caller's destination; `input_left`
        // read/write through the live `s.get()` pointer.
        unsafe {
            num_read = ((*s.get()).read_fn.unwrap())((*s.get()).read_user, ptr as *mut c_void, len);
            (*s.get()).input_left = (*s.get()).input_left.wrapping_sub(num_read);
        }
    }
    (num_read == len) as i32
}

// C comment (ufbx.c:2250-2252):
// 0: Success
// -1: Overfull
// -2: Underfull
// ufbx.c:2253-2453 `ufbxi_huff_build_imp`
#[inline(never)]
pub(crate) fn huff_build_imp(
    tree: &mut HuffTree,
    sym_bits: &[u8],
    sym_extra: &[u32],
    sym_extra_offset: u32,
    fast_bits: u32,
    bits_counts: &mut [u32; HUFF_MAX_BITS],
) -> isize {
    let fast_mask = (1u32 << fast_bits) - 1;

    ufbx_assert!(sym_bits.len() <= HUFF_MAX_VALUE);
    let sym_count = sym_bits.len() as u32;
    tree.num_symbols = sym_count;

    let nonzero_sym_count = sym_count - bits_counts[0];

    let mut total_syms = [0u32; HUFF_MAX_BITS]; // ufbxi_uninit
    let mut first_code = [0u32; HUFF_MAX_BITS]; // ufbxi_uninit

    tree.code_to_sorted[0] = i16::MAX;
    tree.past_max_code[0] = 0;
    total_syms[0] = 0;

    // Clear to uninitialized symbols
    #[cfg(feature = "regression")]
    {
        for i in 0..HUFF_FAST_SIZE {
            tree.fast_sym[i] = HUFF_UNINITIALIZED_SYM;
        }
        for i in 0..HUFF_MAX_VALUE {
            tree.sorted_to_sym[i] = HUFF_UNINITIALIZED_SYM;
        }
        for i in 0..HUFF_MAX_LONG_SYMS {
            tree.long_sym[i] = HUFF_UNINITIALIZED_SYM;
        }
    }

    let mut last_valid_prefix = 0u32;

    // Resolve the maximum code per bit length and ensure that the tree is not
    // overfull or underfull.
    {
        let mut num_codes_left: i32 = 1;
        let mut code = 0u32;
        let mut prev_count = 0u32;
        let mut long_offset = 0u32;
        for bits in 1..HUFF_MAX_BITS as u32 {
            let count = bits_counts[bits as usize];
            code = (code + prev_count) << 1;
            first_code[bits as usize] = code;
            tree.past_max_code[bits as usize] = (code + count) as u16;

            let prev_syms = total_syms[(bits - 1) as usize];
            total_syms[bits as usize] = prev_syms + count;

            // Each bit level doubles the amount of codes and potentially removes some
            num_codes_left = (num_codes_left << 1) - count as i32;
            if num_codes_left < 0 {
                return -1;
            }

            if count > 0 && bits > fast_bits && bits - fast_bits <= HUFF_MAX_LONG_BITS {
                let shift = bits - fast_bits;
                let last_inclusive = if num_codes_left == 0 {
                    (1u32 << shift) - 1u32
                } else {
                    0u32
                };
                let first_prefix = code >> shift;
                let last_prefix = (code + count + last_inclusive) >> shift;
                let mask = (1u32 << shift) - 1u32;
                let half_step = 1u32 << (shift - 1u32);
                for prefix in first_prefix..last_prefix {
                    let rev_prefix = bit_reverse(prefix, fast_bits);
                    tree.fast_sym[rev_prefix as usize] = (mask | (long_offset << 8)) as HuffSym;
                    long_offset += half_step;
                }

                last_valid_prefix = last_prefix;
            }

            if count > 0 {
                tree.code_to_sorted[bits as usize] = (prev_syms as i32 - code as i32) as i16;
            } else {
                tree.code_to_sorted[bits as usize] = i16::MAX;
            }
            prev_count = count;
        }

        // All codes should be used if there's more than one symbol, if there's only one symbol there should be
        // only a single 1-bit code.
        if nonzero_sym_count > 1 && num_codes_left != 0 {
            return -2;
        } else if nonzero_sym_count == 1 && total_syms[1] != 1 {
            return -2;
        }

        // We should always have enough space for long symbols as we support up to 5 (UFBXI_HUFF_MAX_LONG_BITS)
        // bits and the largest tree has 286 symbols. For each bit we may waste at most 2^bits slots (conservative)
        // and in the end we may waste 2^5 slots giving us `286+2+4+8+16+32+32 = 380` (UFBXI_HUFF_MAX_LONG_SYMS)
        ufbx_assert!(long_offset as usize <= HUFF_MAX_LONG_SYMS);
    }

    tree.end_of_block_bits = 0;

    let mut num_extra = 0u32;
    tree.extra_shift_base[0] = 0;
    tree.extra_mask[0] = 0;

    // Fill `fast_sym[]` with error symbols if necessary, we don't need to do this if we have two or more symbols
    // as the tree is guaranteed to be full, which means we will populate the whole `fast_sym[]`
    if nonzero_sym_count <= 1 {
        for i in 0..=fast_mask {
            tree.fast_sym[i as usize] = HUFF_ERROR_SYM;
        }
    }

    // Generate per-length sorted-to-symbol and fast lookup tables
    let mut bits_index = [0u32; HUFF_MAX_BITS];
    for i in 0..sym_count {
        let bits = sym_bits[i as usize] as u32;
        if bits == 0 {
            continue;
        }

        let mut sym = i << 8 | bits;
        if i >= sym_extra_offset {
            let extra = sym_extra[(i - sym_extra_offset) as usize];
            sym += extra;

            // Store length/distance codes with extra values in a table.
            // TODO: This is unnecessary for small values
            if (extra & 0xffff001f) != 0 && (extra & 0x20) == 0 {
                // C: `uint32_t ix = ++num_extra;`
                num_extra += 1;
                let ix = num_extra;
                tree.extra_shift_base[ix as usize] = (extra & 0xffff0000) | bits;
                tree.extra_mask[ix as usize] = ((1u32 << (extra & 0x1f)) - 1) as u16;
                sym = (sym & 0xff) | ix << 8;
            }
        }

        // C: `uint32_t index = bits_index[bits]++;`
        let index = bits_index[bits as usize];
        bits_index[bits as usize] += 1;
        let sorted = total_syms[(bits - 1) as usize] + index;
        tree.sorted_to_sym[sorted as usize] = sym as HuffSym;

        // Reverse the code and fill all fast lookups with the reversed prefix
        let code = first_code[bits as usize] + index;
        let rev_code = bit_reverse(code, bits);

        if bits <= fast_bits {
            let mut fast_sym = sym;
            // The `end` and `fast` flags are mutually exclusive
            if (fast_sym & HUFF_SYM_END) == 0 {
                fast_sym |= HUFF_SYM_FAST;
            }
            let hi_max = 1u32 << (fast_bits - bits);
            for hi in 0..hi_max {
                ufbxi_regression_assert!(
                    nonzero_sym_count <= 1
                        || tree.fast_sym[(rev_code | hi << bits) as usize]
                            == HUFF_UNINITIALIZED_SYM
                );
                tree.fast_sym[(rev_code | hi << bits) as usize] = fast_sym as HuffSym;
            }
        } else if bits <= fast_bits + HUFF_MAX_LONG_BITS
            && (code >> (bits - fast_bits)) < last_valid_prefix
        {
            let fast_sym = tree.fast_sym[(rev_code & fast_mask) as usize] as u32;
            // C: `fast_sym != UFBXI_HUFF_UNINITIALIZED_SYM` — uint32 vs uint16
            // constant, compared after integer promotion (in u32).
            ufbxi_regression_assert!(fast_sym != HUFF_UNINITIALIZED_SYM as u32);
            let mut long_bits = 0u32;

            let mut long_mask = fast_sym;
            while long_bits < HUFF_MAX_LONG_BITS && (long_mask & 1) != 0 {
                long_mask >>= 1;
                long_bits += 1;
            }
            ufbxi_dev_assert!(long_bits >= 1);

            let long_base = fast_sym >> 7u32; // aka (fast_sym >> 8) * 2
            let lo_bits = bits - fast_bits;
            let hi_max = 1u32 << (long_bits - lo_bits);
            let rev_suffix = rev_code >> fast_bits;
            for hi in 0..hi_max {
                ufbxi_regression_assert!(
                    tree.long_sym[(long_base + (rev_suffix | hi << lo_bits)) as usize]
                        == HUFF_UNINITIALIZED_SYM
                );
                tree.long_sym[(long_base + (rev_suffix | hi << lo_bits)) as usize] = sym as HuffSym;
            }
        } else {
            let fast_sym = (code >> (bits - fast_bits)) << 8;
            ufbxi_regression_assert!(
                tree.fast_sym[(rev_code & fast_mask) as usize] == HUFF_UNINITIALIZED_SYM
                    || tree.fast_sym[(rev_code & fast_mask) as usize] == fast_sym as HuffSym
            );
            tree.fast_sym[(rev_code & fast_mask) as usize] = fast_sym as HuffSym;
        }

        // Make sure the end-of-block symbol goes through the slow path
        // Also store the end-of-block code so we can interrupt decoding
        if i == 256 {
            tree.end_of_block_bits = rev_code;
        }
    }

    // Make sure all `fast_sym[]` are filled with an initialized value.
    #[cfg(feature = "regression")]
    {
        for i in 0..HUFF_FAST_SIZE {
            if i <= fast_mask as usize {
                ufbx_assert!(tree.fast_sym[i] != HUFF_UNINITIALIZED_SYM);
            } else {
                ufbx_assert!(tree.fast_sym[i] == HUFF_UNINITIALIZED_SYM);
            }
        }
        for i in 0..nonzero_sym_count as usize {
            ufbx_assert!(tree.sorted_to_sym[i] != HUFF_UNINITIALIZED_SYM);
        }
    }

    0
}

// C comment (ufbx.c:2455-2457):
// 0: Success
// -1: Overfull
// -2: Underfull
// ufbx.c:2458-2472 `ufbxi_huff_build`
#[inline(never)]
pub(crate) fn huff_build(
    tree: &mut HuffTree,
    sym_bits: &[u8],
    sym_extra: &[u32],
    sym_extra_offset: u32,
    fast_bits: u32,
) -> isize {
    // Count the number of codes per bit length
    // `bits_counts[0]` contains the number of non-used symbols
    // C: `uint32_t bits_counts[UFBXI_HUFF_MAX_BITS]; // ufbxi_uninit` + memset
    let mut bits_counts = [0u32; HUFF_MAX_BITS];
    for &sym_bits in sym_bits {
        let bits = sym_bits as u32;
        ufbx_assert!((bits as usize) < HUFF_MAX_BITS);
        bits_counts[bits as usize] += 1;
    }

    huff_build_imp(
        tree,
        sym_bits,
        sym_extra,
        sym_extra_offset,
        fast_bits,
        &mut bits_counts,
    )
}

// ufbx.c:2474-2508 `ufbxi_huff_decode_bits`
// C: `static ufbxi_forceinline ufbxi_huff_sym`.
#[inline(always)]
fn huff_decode_bits(tree: &HuffTree, bits: u64, fast_bits: u32, fast_mask: u32) -> HuffSym {
    let mut sym: HuffSym = tree.fast_sym[(bits & fast_mask as u64) as usize];
    ufbxi_regression_assert!(sym != HUFF_UNINITIALIZED_SYM);

    if (sym as u32 & (HUFF_SYM_FAST | HUFF_SYM_END)) != 0 {
        return sym;
    }

    let mut tail = (bits >> fast_bits) as u32;
    let long_mask = huff_sym_long_mask(sym);
    if long_mask != 0 {
        sym = tree.long_sym[(huff_sym_long_offset(sym) + (tail & long_mask)) as usize];
        ufbxi_regression_assert!(sym != HUFF_UNINITIALIZED_SYM);
        return sym;
    }

    ufbxi_dev_assert!(fast_bits <= 8);

    let mut code = huff_sym_value(sym);
    let mut num_bits = fast_bits;
    loop {
        code = code << 1 | (tail & 1);
        tail >>= 1;
        num_bits += 1;

        ufbxi_regression_assert!((num_bits as usize) < HUFF_MAX_BITS);
        if code < tree.past_max_code[num_bits as usize] as u32 {
            // C: `sorted_to_sym[(int32_t)code + (int32_t)tree->code_to_sorted[num_bits]]`
            sym = tree.sorted_to_sym
                [(code as i32 + tree.code_to_sorted[num_bits as usize] as i32) as usize];
            ufbxi_regression_assert!(sym != HUFF_UNINITIALIZED_SYM);
            return sym;
        }
    }
}

// ufbx.c:2510-2538 `ufbxi_init_static_huff`
// NOTE: `input` may be NULL (called with NULL from `ufbxi_inflate_init_retain`).
#[inline(never)]
pub(crate) unsafe fn init_static_huff(trees: *mut Trees, input: *const InflateInput) {
    // `trees` is the sole raw pointer to that `Trees` in this function (rule
    // 4): local exclusive borrow in place of repeated `(*trees).field`
    // derefs. `input` is left as a raw pointer — it may legitimately be
    // NULL here (see the fn doc comment), so an unconditional `&*input`
    // reference is not obviously sound.
    // SAFETY: the caller's contract is that `trees` points at a valid, uniquely
    // owned `Trees` for this call.
    let trees = unsafe { &mut *trees };
    let mut err: isize = 0;

    // Override `fast_bits` if necessary, this must always be valid as it's checked in the beginning of `ufbx_inflate()`.
    // SAFETY: `(*input)` is only reached when `input` is non-null (short-circuit
    // above); a non-null `input` is a valid `InflateInput` per the caller.
    if !input.is_null() && unsafe { (*input).internal_fast_bits } != 0 {
        // SAFETY: `input` is non-null here (checked above), so the deref is valid.
        trees.fast_bits = unsafe { (*input).internal_fast_bits } as u32;
        ufbx_assert!(!(trees.fast_bits < 1 || trees.fast_bits == 9 || trees.fast_bits > 10));
    } else {
        trees.fast_bits = HUFF_FAST_BITS;
    }
    let fast_bits = trees.fast_bits;

    // 0-143: 8 bits, 144-255: 9 bits, 256-279: 7 bits, 280-287: 8 bits
    let mut lit_length_bits = [0u8; 288]; // ufbxi_uninit
    lit_length_bits[0..144].fill(8);
    lit_length_bits[144..256].fill(9);
    lit_length_bits[256..280].fill(7);
    lit_length_bits[280..288].fill(8);
    err |= huff_build(
        trees.lit_length_mut(),
        &lit_length_bits,
        &DEFLATE_LENGTH_LUT,
        256,
        fast_bits,
    );

    // "Distance codes 0-31 are represented by (fixed-length) 5-bit codes"
    let mut dist_bits = [0u8; 32]; // ufbxi_uninit
    dist_bits[0..32].fill(5);
    err |= huff_build(
        trees.dist_mut(),
        &dist_bits,
        &DEFLATE_DIST_LUT,
        0,
        fast_bits,
    );

    // Building the static trees cannot fail as we use pre-defined code lengths.
    ufbxi_ignore!(err);
    ufbx_assert!(err == 0);
}

// ufbx.c:2540-2602 `ufbxi_decode_dynamic_huff_bits`
#[inline(never)]
fn decode_dynamic_huff_bits(
    dc: &DeflateContext,
    huff_code_length: &HuffTree,
    code_lengths: &mut [u8],
) -> isize {
    // `(*dc.get()).stream` holds a self-referential `buffer`→`local_buffer` pointer (see
    // `bit_stream_init`), so `dc` stays raw and is derefed as `(*dc.get()).field` to
    // avoid a whole-struct retag invalidating that interior pointer.

    let mut bits = dc.stream_view().bits();
    let mut left = dc.stream_view().left();
    let mut data = dc.stream_view().chunk_ptr();

    let num_symbols = code_lengths.len() as u32;
    let mut symbol_index = 0u32;
    let mut prev = 0u8;
    while symbol_index < num_symbols {
        // SAFETY: the locals mirror the stream's `bits`/`left`/`chunk_ptr`, and
        // `dc.stream_view()` is `dc`'s own live bit-stream view.
        unsafe { bit_refill(&mut bits, &mut left, &mut data, dc.stream_view()) };
        if dc.stream_view().cancelled() {
            return -28;
        }

        let sym: HuffSym = huff_decode_bits(
            huff_code_length,
            bits,
            HUFF_CODELEN_FAST_BITS,
            HUFF_CODELEN_FAST_MASK,
        );
        ufbxi_regression_assert!(sym != HUFF_UNINITIALIZED_SYM);
        if sym == HUFF_ERROR_SYM {
            return -21;
        }

        let inst = huff_sym_value(sym);
        let sym_len = huff_sym_total_bits(sym);

        bits >>= sym_len;
        left -= sym_len as usize;

        if inst <= 15 {
            // "0 - 15: Represent code lengths of 0 - 15"
            prev = inst as u8;
            // C: `code_lengths[symbol_index++] = (uint8_t)inst;`
            code_lengths[symbol_index as usize] = inst as u8;
            symbol_index += 1;
        } else if inst == 16 {
            // "16: Copy the previous code length 3 - 6 times. The next 2 bits indicate repeat length."
            let num = 3 + (bits as u32 & 0x3);
            bits >>= 2;
            left -= 2;
            if symbol_index + num > num_symbols {
                return -18;
            }
            // C: memset(code_lengths + symbol_index, prev, num)
            code_lengths[symbol_index as usize..(symbol_index + num) as usize].fill(prev);
            symbol_index += num;
        } else if inst == 17 {
            // "17: Repeat a code length of 0 for 3 - 10 times. (3 bits of length)"
            let num = 3 + (bits as u32 & 0x7);
            bits >>= 3;
            left -= 3;
            if symbol_index + num > num_symbols {
                return -19;
            }
            code_lengths[symbol_index as usize..(symbol_index + num) as usize].fill(0);
            symbol_index += num;
            prev = 0;
        } else if inst == 18 {
            // "18: Repeat a code length of 0 for 11 - 138 times (7 bits of length)"
            let num = 11 + (bits as u32 & 0x7f);
            bits >>= 7;
            left -= 7;
            if symbol_index + num > num_symbols {
                return -20;
            }
            code_lengths[symbol_index as usize..(symbol_index + num) as usize].fill(0);
            symbol_index += num;
            prev = 0;
        } else {
            return -6;
        }
    }

    dc.stream_view().set_bits(bits);
    dc.stream_view().set_left(left);
    dc.stream_view().set_chunk_ptr(data);

    0
}

// ufbx.c:2603-2662 `ufbxi_init_dynamic_huff`
#[inline(never)]
fn init_dynamic_huff(dc: &DeflateContext, trees: &mut Trees) -> isize {
    // `(*dc.get()).stream` holds a self-referential `buffer`→`local_buffer` pointer (see
    // `bit_stream_init`), so `dc` stays raw and is derefed as `(*dc.get()).field` to
    // avoid a whole-struct retag invalidating that interior pointer.

    let mut bits = dc.stream_view().bits();
    let mut left = dc.stream_view().left();
    let mut data = dc.stream_view().chunk_ptr();
    // SAFETY: the locals mirror the stream's `bits`/`left`/`chunk_ptr`, and
    // `dc.stream_view()` is `dc`'s own live bit-stream view.
    unsafe { bit_refill(&mut bits, &mut left, &mut data, dc.stream_view()) };
    if dc.stream_view().cancelled() {
        return -28;
    }

    trees.fast_bits = dc.fast_bits();

    // The header contains the number of Huffman codes in each of the three trees.
    let num_lit_lengths = 257 + (bits & 0x1f) as u32;
    let num_dists = 1 + (bits >> 5 & 0x1f) as u32;
    let num_code_lengths = 4 + (bits >> 10 & 0xf) as u32;
    bits >>= 14;
    left -= 14;

    // C: `uint8_t code_lengths[UFBXI_HUFF_MAX_COMBINED_SYMS]; // ufbxi_uninit`
    // followed by `memset(code_lengths, 0, UFBXI_HUFF_CODELEN_SYMS)`; zero-init
    // covers the memset, C never reads past what is subsequently written.
    let mut code_lengths = [0u8; HUFF_MAX_COMBINED_SYMS]; // ufbxi_uninit

    // Code lengths for the "code length" Huffman tree are represented literally
    // 3 bits in order of: 16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15 up to
    // `num_code_lengths`, rest of the code lengths are 0 (unused)

    for len_i in 0..num_code_lengths as usize {
        if len_i == 14 {
            // SAFETY: the locals mirror the stream's `bits`/`left`/`chunk_ptr`,
            // and `dc.stream_view()` is `dc`'s own live bit-stream view.
            unsafe { bit_refill(&mut bits, &mut left, &mut data, dc.stream_view()) };
            if dc.stream_view().cancelled() {
                return -28;
            }
        }
        code_lengths[DEFLATE_CODE_LENGTH_PERMUTATION[len_i] as usize] = (bits as u32 & 0x7) as u8;
        bits >>= 3;
        left -= 3;
    }

    dc.stream_view().set_bits(bits);
    dc.stream_view().set_left(left);
    dc.stream_view().set_chunk_ptr(data);

    // C: `ufbxi_huff_tree huff_code_length; // ufbxi_uninit` — zero-init,
    // `ufbxi_huff_build` writes everything that is later read.
    // SAFETY: `HuffTree` is a plain POD of integer arrays, so an all-zero bit
    // pattern is a valid value.
    let mut huff_code_length: HuffTree = unsafe { core::mem::zeroed() }; // ufbxi_uninit
    let mut err: isize; // ufbxi_uninit

    // Build the temporary "code length" Huffman tree used to encode the actual
    // trees used to compress the data. Use that to build the literal/length and
    // distance trees.
    err = huff_build(
        &mut huff_code_length,
        &code_lengths[..HUFF_CODELEN_SYMS],
        &[],
        i32::MAX as u32,
        HUFF_CODELEN_FAST_BITS,
    );
    if err != 0 {
        return -14 + 1 + err;
    }

    err = decode_dynamic_huff_bits(
        dc,
        &huff_code_length,
        &mut code_lengths[..(num_lit_lengths + num_dists) as usize],
    );
    if err != 0 {
        return err;
    }

    err = huff_build(
        trees.lit_length_mut(),
        &code_lengths[..num_lit_lengths as usize],
        &DEFLATE_LENGTH_LUT,
        256,
        dc.fast_bits(),
    );
    if err != 0 {
        return if err == -7 { -28 } else { -16 + 1 + err };
    }

    err = huff_build(
        trees.dist_mut(),
        &code_lengths[num_lit_lengths as usize..(num_lit_lengths + num_dists) as usize],
        &DEFLATE_DIST_LUT,
        0,
        dc.fast_bits(),
    );
    if err != 0 {
        return if err == -7 { -28 } else { -22 + 1 + err };
    }

    0
}

// ufbx.c:2664-2803 `ufbxi_adler32`
// C-parity: C has three inner-loop variants — SSE (`UFBXI_HAS_SSE`), a scalar
// 64-bit SWAR loop (`UFBX_LITTLE_ENDIAN`), and the plain byte loop. All three
// produce bit-identical sums (the SIMD/SWAR forms are pure strength
// reductions of the same modular arithmetic); the Rust port carries the SWAR
// branch (ufbx.c:2746-2790) on little-endian targets and the plain loop
// otherwise — the SSE branch is intentionally not ported.
#[inline(never)]
pub(crate) fn adler32(data: &[u8]) -> u32 {
    let mut a: FastUint = 1;
    let mut b: FastUint = 0;
    let mut p = 0usize;

    // Adler-32 consists of two running sums modulo 65521. As an optimization
    // we can accumulate N sums before applying the modulo, where N depends on
    // the size of the type holding the sum.
    let num_before_wrap: FastUint = if size_of::<FastUint>() == 8 {
        380368439
    } else {
        5552
    };

    let mut size_left = data.len() as FastUint;
    while size_left > 0 {
        let num = if size_left <= num_before_wrap {
            size_left
        } else {
            num_before_wrap
        };
        size_left -= num;
        let end = p + num as usize;

        // Align to 16 bytes
        while p != end && !is_aligned(data[p..].as_ptr(), 16) {
            a += data[p] as FastUint;
            b += a;
            p += 1;
        }

        // ufbx.c:2746-2790 `#elif UFBX_LITTLE_ENDIAN` scalar SWAR branch
        #[cfg(target_endian = "little")]
        {
            loop {
                let chunk_size = min_sz(end - p, 256 * 8 / 4) & !0xfusize;
                if chunk_size == 0 {
                    break;
                }
                let chunk_end = p + chunk_size;

                let mut s1_lo: u64 = 0;
                let mut s1_hi: u64 = 0;
                let mut tmp: u64;
                let mut s2: u64 = 0;
                let mask8: u64 = 0x00ff00ff00ff00ff;
                let mask16: u64 = 0x0000ffff0000ffff;

                while p != chunk_end {
                    // C: `*(const uint64_t*)p` — `p` is 16-aligned here;
                    // little-endian native load == `from_le_bytes`.
                    let d0 = u64::from_le_bytes([
                        data[p],
                        data[p + 1],
                        data[p + 2],
                        data[p + 3],
                        data[p + 4],
                        data[p + 5],
                        data[p + 6],
                        data[p + 7],
                    ]);
                    let d1 = u64::from_le_bytes([
                        data[p + 8],
                        data[p + 9],
                        data[p + 10],
                        data[p + 11],
                        data[p + 12],
                        data[p + 13],
                        data[p + 14],
                        data[p + 15],
                    ]);

                    tmp = s1_lo + s1_hi;
                    s1_lo += d0 & mask8;
                    s1_hi += (d0 >> 8) & mask8;

                    tmp += s1_lo + s1_hi;
                    s1_lo += d1 & mask8;
                    s1_hi += (d1 >> 8) & mask8;

                    s2 += (tmp & mask16) + ((tmp >> 16) & mask16);
                    p += 16;
                }

                let mut s1 = s1_lo + s1_hi;
                s1 = (s1 & mask16) + ((s1 >> 16u32) & mask16);
                let s1_sum = (s1 + (s1 >> 32u32)) as FastUint;

                let mut s2_sum = ((s2 + (s2 >> 32u32)) as FastUint) * 8;
                s2_sum += ((s1_lo >> 0) as FastUint & 0xffff) * 8;
                s2_sum += ((s1_hi >> 0) as FastUint & 0xffff) * 7;
                s2_sum += ((s1_lo >> 16) as FastUint & 0xffff) * 6;
                s2_sum += ((s1_hi >> 16) as FastUint & 0xffff) * 5;
                s2_sum += ((s1_lo >> 32) as FastUint & 0xffff) * 4;
                s2_sum += ((s1_hi >> 32) as FastUint & 0xffff) * 3;
                s2_sum += ((s1_lo >> 48) as FastUint & 0xffff) * 2;
                s2_sum += ((s1_hi >> 48) as FastUint & 0xffff) * 1;

                b += chunk_size as FastUint * a;
                a += s1_sum & 0xffffffff;
                b += s2_sum & 0xffffffff;
            }
        }

        while p != end {
            a += data[p] as FastUint;
            b += a;
            p += 1;
        }

        a %= 65521;
        b %= 65521;
    }

    ((b << 16) | (a & 0xffff)) as u32
}

// ufbx.c:2805-2904 `ufbxi_inflate_block_slow`
#[inline(never)]
pub(crate) unsafe fn inflate_block_slow(
    dc: &DeflateContext,
    trees: *mut Trees,
    max_symbols: usize,
) -> i32 {
    // `(*dc.get()).stream` holds a self-referential `buffer`→`local_buffer` pointer (see
    // `bit_stream_init`), so `dc` stays raw and is derefed as `(*dc.get()).field` to
    // avoid a whole-struct retag invalidating that interior pointer. `trees` is
    // not self-referential and only ever read here, so a shared borrow suffices.
    // SAFETY: the caller's contract is that `trees` points at a valid, fully
    // built `Trees` that stays borrowable for this call.
    let trees = unsafe { &*trees };

    let mut max_symbols = max_symbols;
    let mut out_ptr = dc.out_ptr();
    let out_begin = dc.out_begin();
    let out_end = dc.out_end();

    let fast_bits = trees.fast_bits;
    let fast_mask = (1u32 << fast_bits) - 1;

    let mut bits = dc.stream_view().bits();
    let mut left = dc.stream_view().left();
    let mut data = dc.stream_view().chunk_ptr();

    loop {
        // C: `if (max_symbols-- == 0) break;` (size_t; wraps past zero)
        let prev_max_symbols = max_symbols;
        max_symbols = max_symbols.wrapping_sub(1);
        if prev_max_symbols == 0 {
            break;
        }

        // SAFETY: the locals mirror the stream's `bits`/`left`/`chunk_ptr`, and
        // `dc.stream_view()` is `dc`'s own live bit-stream view.
        unsafe { bit_refill(&mut bits, &mut left, &mut data, dc.stream_view()) };
        let sym_bits = bits;

        let sym0: HuffSym = huff_decode_bits(trees.lit_length(), bits, fast_bits, fast_mask);
        ufbxi_regression_assert!(sym0 != HUFF_UNINITIALIZED_SYM);

        let sym0_bits = huff_sym_total_bits(sym0);

        bits >>= sym0_bits;
        // C-parity: `left` is size_t in C and may transiently wrap below zero
        // on adversarial input; it is masked back by `left |= 56` on refill.
        left = left.wrapping_sub(sym0_bits as usize);
        if (sym0 as u32 & HUFF_SYM_END) != 0 {
            if huff_sym_value(sym0) != 0 {
                return -13;
            }

            dc.set_out_ptr(out_ptr);
            dc.stream_view().set_bits(bits);
            dc.stream_view().set_left(left);
            dc.stream_view().set_chunk_ptr(data);
            return 0;
        } else if (sym0 as u32 & HUFF_SYM_MATCH) == 0 {
            if out_ptr == out_end {
                return -10;
            }
            // C: `*out_ptr++ = (char)ufbxi_huff_sym_value(sym0);`
            // SAFETY: `out_ptr != out_end` (checked just above), so it addresses
            // a writable byte, and advancing by one lands at most at `out_end`.
            unsafe {
                *out_ptr = huff_sym_value(sym0) as u8;
                out_ptr = out_ptr.add(1);
            }
            continue;
        }

        let sym0_value = huff_sym_value(sym0);
        let len_shift_base = trees.lit_length().extra_shift_base[sym0_value as usize];
        let len_mask = trees.lit_length().extra_mask[sym0_value as usize];
        let length = (len_shift_base >> 16)
            + (wrap_shr64(sym_bits, len_shift_base) & len_mask as u64) as u32;

        let sym1: HuffSym = huff_decode_bits(trees.dist(), bits, fast_bits, fast_mask);
        ufbxi_regression_assert!(sym1 != HUFF_UNINITIALIZED_SYM);
        if (sym1 as u32 & HUFF_SYM_END) != 0 {
            return -11;
        }

        let sym1_bits = huff_sym_total_bits(sym1);

        bits >>= sym1_bits;
        left = left.wrapping_sub(sym1_bits as usize);

        let sym1_value = huff_sym_value(sym1);
        let dist_shift_base = trees.dist().extra_shift_base[sym1_value as usize];
        let dist_mask = trees.dist().extra_mask[sym1_value as usize];
        let distance = (dist_shift_base >> 16)
            + (wrap_shr64(sym_bits, dist_shift_base + sym0 as u32) & dist_mask as u64) as u32;

        // Bounds checking
        // SAFETY: `out_ptr`/`out_end` and `out_begin`/`out_ptr` are pairs of
        // positions in the one output buffer, so `offset_from` is in bounds.
        let out_space = to_size(unsafe { out_end.offset_from(out_ptr) });
        if distance as isize > unsafe { out_ptr.offset_from(out_begin) }
            || length as usize > out_space
        {
            return -12;
        }

        // Copy the match
        // SAFETY: the bounds check above guarantees `distance <= out_ptr -
        // out_begin` and `length <= out_space`, so `out_ptr - distance` and
        // `out_ptr + length` both land inside the output buffer.
        let mut src: *const u8 = unsafe { out_ptr.sub(distance as usize) };
        let mut dst = out_ptr;
        let end = unsafe { dst.add(length as usize) };
        out_ptr = unsafe { out_ptr.add(length as usize) };

        let mut length = length;
        if out_space >= length as usize + 16 {
            let min_dist = if length < 16 { length } else { 16 };
            if distance >= min_dist {
                // SAFETY: `out_space >= length + 16` gives 16 bytes of slack at
                // `dst`; `copy_16_bytes` is an overlap-tolerant load-then-store,
                // and `distance >= min_dist` guarantees the first `length` bytes
                // — the only ones relied upon — copy correctly even when
                // `distance < 16` lets the 16-byte windows overlap.
                unsafe { copy_16_bytes(dst, src) };
                while length > 16 {
                    // SAFETY: `length > 16` bytes remain and the 16-byte slack
                    // keeps `src + 16`/`dst + 16` within the buffer.
                    unsafe {
                        src = src.add(16);
                        dst = dst.add(16);
                    }
                    length -= 16;
                    // SAFETY: same 16-byte-slack invariant as the first copy.
                    unsafe { copy_16_bytes(dst, src) };
                }
            } else {
                while dst != end {
                    // C: `*dst++ = *src++;`
                    // SAFETY: `dst != end` keeps `dst` inside the `length`-byte
                    // match region and `src` inside its earlier source region.
                    unsafe {
                        *dst = *src;
                        dst = dst.add(1);
                        src = src.add(1);
                    }
                }
            }
        } else {
            while dst != end {
                // SAFETY: `dst != end` keeps `dst` inside the `length`-byte match
                // region and `src` inside its earlier source region.
                unsafe {
                    *dst = *src;
                    dst = dst.add(1);
                    src = src.add(1);
                }
            }
        }
    }

    dc.set_out_ptr(out_ptr);
    dc.stream_view().set_bits(bits);
    dc.stream_view().set_left(left);
    dc.stream_view().set_chunk_ptr(data);
    1
}

// ufbx.c:2906 `ufbx_static_assert(inflate_huff_fast_bits, ...)`
const _: () = assert!(HUFF_FAST_BITS <= 11); // `fast lit, fast len, slow dist` in 56 bits
                                             // ufbx.c:2907 `ufbx_static_assert(inflate_huff_long_bits, ...)`
const _: () = assert!(HUFF_FAST_BITS + HUFF_MAX_LONG_BITS >= 15); // Largest code fits in a single long lookup

// ufbx.c:2909-3091 `ufbxi_inflate_block_fast`
// Optimized version of `ufbxi_inflate_block_slow()`.
// Has a lot of assumptions (see asserts) and does not call _any_ (even forceinlined) functions.
#[inline(never)]
#[allow(unused_assignments)] // trailing `refill_bits` write of the C macro
pub(crate) unsafe fn inflate_block_fast(dc: &DeflateContext, trees: *mut Trees) -> i32 {
    // `(*dc.get()).stream` holds a self-referential `buffer`→`local_buffer` pointer (see
    // `bit_stream_init`), so `dc` stays raw and is derefed as `(*dc.get()).field` to
    // avoid a whole-struct retag invalidating that interior pointer. `trees` is
    // not self-referential and only ever read here, so a shared borrow suffices;
    // `tree_lit_length`/`tree_dist` stay raw pointers as-is since the
    // refill/decode macro below dereferences them directly.
    // SAFETY: the caller's contract is that `trees` points at a valid, fully
    // built `Trees` that stays borrowable for this call.
    let trees = unsafe { &*trees };

    ufbxi_dev_assert!(!dc.stream_view().cancelled());
    ufbxi_dev_assert!(trees.fast_bits == HUFF_FAST_BITS);
    // SAFETY: `chunk_yield` and `chunk_ptr` are two positions in the same chunk,
    // so `offset_from` is in bounds.
    ufbxi_dev_assert!(
        unsafe {
            dc.stream_view()
                .chunk_yield()
                .offset_from(dc.stream_view().chunk_ptr())
        } >= INFLATE_FAST_MIN_IN as isize
    );
    // SAFETY: `out_end`/`out_ptr` are positions in the one output buffer, so
    // `offset_from` is in bounds.
    ufbxi_dev_assert!(
        unsafe { dc.out_end().offset_from(dc.out_ptr()) } >= INFLATE_FAST_MIN_OUT as isize
    );

    let mut out_ptr = dc.out_ptr();
    let out_begin: *mut u8 = dc.out_begin();
    // SAFETY: the caller's contract (checked for real by `inflate`'s
    // `fast_viable` guard; the dev asserts above only re-state it) gives at
    // least `INFLATE_FAST_MIN_OUT` writable bytes between `out_ptr` and
    // `out_end`, so backing `out_end` up by that count stays within the buffer.
    let out_end: *mut u8 = unsafe { dc.out_end().sub(INFLATE_FAST_MIN_OUT) };

    let tree_lit_length: *const HuffTree = trees.lit_length();
    let tree_dist: *const HuffTree = trees.dist();

    let mut bits = dc.stream_view().bits();
    let mut left = dc.stream_view().left();
    let mut data = dc.stream_view().chunk_ptr();
    // SAFETY: the caller's contract (checked for real at the call site in
    // `inflate`; the dev assert above only re-states it) gives at least
    // `INFLATE_FAST_MIN_IN` bytes between `chunk_ptr` and `chunk_yield`, so
    // backing `chunk_yield` up by that count stays within the chunk.
    let data_end: *const u8 = unsafe { dc.stream_view().chunk_yield().sub(INFLATE_FAST_MIN_IN) };

    let mut sym01_bits: u64;
    let mut sym0: HuffSym;
    let mut sym1: HuffSym;
    // SAFETY: `data` is the current chunk position, kept at least 8 bytes before
    // `chunk_real_end`, so a 64-bit read is in bounds.
    let mut refill_bits = unsafe { read_u64(crate::prelude::slice_from_ptr(data, 8)) };

    // C: `#define ufbxi_fast_inflate_refill_and_decode()` (function-local macro;
    // the free identifiers resolve to the locals above at each expansion site).
    macro_rules! fast_inflate_refill_and_decode {
        () => {{
            macro_bit_refill_fast!(bits, left, data, refill_bits);
            sym01_bits = bits;
            sym0 = (*tree_lit_length).fast_sym[(sym01_bits as usize) & HUFF_FAST_MASK];
            sym1 = (*(if (sym0 as u32 & HUFF_SYM_MATCH) != 0 {
                tree_dist
            } else {
                tree_lit_length
            }))
            .fast_sym[(wrap_shr64(sym01_bits, sym0 as u32) as usize) & HUFF_FAST_MASK];
            refill_bits = read_u64(crate::prelude::slice_from_ptr(data, 8));
        }};
    }

    // C: `#define ufbxi_fast_inflate_should_continue()`
    macro_rules! fast_inflate_should_continue {
        () => {
            (data_end.offset_from(data) | out_end.offset_from(out_ptr)) >= 0
        };
    }

    // SAFETY: the macro refills `bits` from `data` (kept 8+ bytes before the
    // chunk end) and indexes the two live `fast_sym` tables through
    // `tree_lit_length`/`tree_dist`, whose targets are the borrowed `trees`.
    unsafe { fast_inflate_refill_and_decode!() };

    loop {
        if ((sym0 as u32 & sym1 as u32) & HUFF_SYM_FAST) != 0 {
            bits = wrap_shr64(sym01_bits, sym0 as u32 + sym1 as u32);
            // C-parity: size_t wrap (masked back by `left |= 56` on refill).
            left = left.wrapping_sub(((sym0 as u32 + sym1 as u32) & 0x3f) as usize);

            if ((sym0 as u32 | sym1 as u32) & HUFF_SYM_MATCH) == 0 {
                // Literal, Literal
                // -> Output the two literals and loop back to start.

                // SAFETY: the fast path keeps at least `INFLATE_FAST_MIN_OUT`
                // bytes of headroom past `out_ptr` (bounds re-checked each
                // iteration), so writing two bytes and advancing by two is in
                // bounds.
                unsafe {
                    *out_ptr.add(0) = huff_sym_value(sym0) as u8;
                    *out_ptr.add(1) = huff_sym_value(sym1) as u8;
                    out_ptr = out_ptr.add(2);
                }

                // SAFETY: as at the first invocation — refills from `data` and
                // indexes the live `fast_sym` tables.
                unsafe { fast_inflate_refill_and_decode!() };
                // SAFETY: the macro compares `data_end`/`data` and
                // `out_end`/`out_ptr`, each a pair in one object.
                if unsafe { fast_inflate_should_continue!() } {
                    continue;
                }
                break;
            } else if (sym0 as u32 & HUFF_SYM_MATCH) == 0 {
                // Literal, Match, (Distance)
                // -> Output a single literal, decode the missing distance and fall through to match.

                // SAFETY: at least `INFLATE_FAST_MIN_OUT` bytes of headroom past
                // `out_ptr`, so writing one byte and advancing by one is in bounds.
                unsafe {
                    *out_ptr.add(0) = huff_sym_value(sym0) as u8;
                    out_ptr = out_ptr.add(1);
                }

                sym01_bits = wrap_shr64(sym01_bits, sym0 as u32);

                // This must fit as literals never have extra bits and the match length is fast so:
                // 10 (lit) + 10 (len code) + 5 (len extra) + 15 (dist code) + 13 (dist extra) = 53 <= 56
                sym0 = sym1;
                // SAFETY: `tree_dist` targets the borrowed live distance tree;
                // `fast_sym` is indexed by a `HUFF_FAST_MASK`-masked value.
                sym1 = unsafe { (*tree_dist).fast_sym[(bits as usize) & HUFF_FAST_MASK] };

                if (sym1 as u32 & HUFF_SYM_FAST) == 0 {
                    // Slow sym1
                    if (sym1 as u32 & HUFF_SYM_END) != 0 {
                        return -11;
                    }
                    let tail = (bits >> HUFF_FAST_BITS) as u32;
                    let long_mask = huff_sym_long_mask(sym1);
                    // SAFETY: `tree_dist` targets the live distance tree; the
                    // `long_sym` index is a built long-offset plus a masked tail,
                    // which the tree construction sizes to fit.
                    sym1 = unsafe {
                        (*tree_dist).long_sym
                            [(huff_sym_long_offset(sym1) + (tail & long_mask)) as usize]
                    };
                    if (sym1 as u32 & HUFF_SYM_END) != 0 {
                        return -11;
                    }
                }

                bits = wrap_shr64(bits, sym1 as u32);
                left = left.wrapping_sub((sym1 as u32 & 0x3f) as usize);
            } else {
                // Match, Distance
                // -> Fall through to match copy.
            }
        } else {
            if (sym0 as u32 & (HUFF_SYM_FAST | HUFF_SYM_END)) == 0 {
                // Slow sym0
                let tail = (sym01_bits >> HUFF_FAST_BITS) as u32;
                let long_mask = huff_sym_long_mask(sym0);
                // SAFETY: `tree_lit_length` targets the live lit/length tree; the
                // `long_sym` index is a built long-offset plus a masked tail,
                // sized to fit by tree construction.
                sym0 = unsafe {
                    (*tree_lit_length).long_sym
                        [(huff_sym_long_offset(sym0) + (tail & long_mask)) as usize]
                };
            }

            let sym0_bits = huff_sym_total_bits(sym0);
            bits >>= sym0_bits;
            left = left.wrapping_sub(sym0_bits as usize);

            if (sym0 as u32 & HUFF_SYM_END) != 0 {
                if huff_sym_value(sym0) != 0 {
                    return -13;
                }
                dc.set_out_ptr(out_ptr);
                dc.stream_view().set_bits(bits);
                dc.stream_view().set_left(left);
                dc.stream_view().set_chunk_ptr(data);
                return 0;
            }

            if (sym0 as u32 & HUFF_SYM_MATCH) != 0 {
                // SAFETY: `tree_dist` targets the live distance tree; `fast_sym`
                // is indexed by a `HUFF_FAST_MASK`-masked value.
                sym1 = unsafe { (*tree_dist).fast_sym[(bits as usize) & HUFF_FAST_MASK] };

                if (sym1 as u32 & HUFF_SYM_FAST) == 0 {
                    // Slow sym1
                    if (sym1 as u32 & HUFF_SYM_END) != 0 {
                        return -11;
                    }
                    let tail = (bits >> HUFF_FAST_BITS) as u32;
                    let long_mask = huff_sym_long_mask(sym1);
                    // SAFETY: `tree_dist` targets the live distance tree; the
                    // `long_sym` index is a built long-offset plus a masked tail,
                    // sized to fit by tree construction.
                    sym1 = unsafe {
                        (*tree_dist).long_sym
                            [(huff_sym_long_offset(sym1) + (tail & long_mask)) as usize]
                    };
                    if (sym1 as u32 & HUFF_SYM_END) != 0 {
                        return -11;
                    }
                }

                bits = wrap_shr64(bits, sym1 as u32);
                left = left.wrapping_sub((sym1 as u32 & 0x3f) as usize);
            } else {
                // C: `*out_ptr++ = (char)ufbxi_huff_sym_value(sym0);`
                // SAFETY: at least `INFLATE_FAST_MIN_OUT` bytes of headroom past
                // `out_ptr`, so writing one byte and advancing by one is in bounds.
                unsafe {
                    *out_ptr = huff_sym_value(sym0) as u8;
                    out_ptr = out_ptr.add(1);
                }

                // SAFETY: as at the first invocation — refills from `data` and
                // indexes the live `fast_sym` tables.
                unsafe { fast_inflate_refill_and_decode!() };
                // SAFETY: the macro compares `data_end`/`data` and
                // `out_end`/`out_ptr`, each a pair in one object.
                if unsafe { fast_inflate_should_continue!() } {
                    continue;
                }
                break;
            }
        }

        let sym0_value = huff_sym_value(sym0);
        let len_shift_base = trees.lit_length().extra_shift_base[sym0_value as usize];
        let len_mask = trees.lit_length().extra_mask[sym0_value as usize];
        let mut length = (len_shift_base >> 16)
            + (wrap_shr64(sym01_bits, len_shift_base) & len_mask as u64) as u32;

        let sym1_value = huff_sym_value(sym1);
        let dist_shift_base = trees.dist().extra_shift_base[sym1_value as usize];
        let dist_mask = trees.dist().extra_mask[sym1_value as usize];
        let distance = (dist_shift_base >> 16)
            + (wrap_shr64(sym01_bits, dist_shift_base + sym0 as u32) & dist_mask as u64) as u32;

        // SAFETY: as at the first invocation — refills from `data` and indexes
        // the live `fast_sym` tables.
        unsafe { fast_inflate_refill_and_decode!() };

        // Bounds checking: We don't actually handle the error here, just bail out to the slow implementation
        // SAFETY: `out_end`/`out_ptr` and `out_begin`/`out_ptr` are pairs of
        // positions in the one output buffer, so `offset_from` is in bounds.
        let dst_space = unsafe { out_end.offset_from(out_ptr) } - length as isize
            + INFLATE_FAST_MIN_OUT as isize;
        let src_space = unsafe { out_ptr.offset_from(out_begin) } - distance as isize;
        if (dst_space | src_space) < 0 {
            return -12;
        }

        // SAFETY: `src_space >= 0` gives `distance <= out_ptr - out_begin`, and
        // `dst_space >= 0` gives exactly `length` bytes of room up to the real
        // buffer end (the `INFLATE_FAST_MIN_OUT` backed out of `out_end` is
        // folded back into `dst_space`), so `out_ptr - distance` and `out_ptr +
        // length` land inside the output buffer.
        let mut src: *const u8 = unsafe { out_ptr.sub(distance as usize) };
        let mut dst = out_ptr;
        let end = unsafe { dst.add(length as usize) };
        out_ptr = unsafe { out_ptr.add(length as usize) };

        // Copy the match

        let min_dist = if length < 16 { length } else { 16 };
        if distance >= min_dist as u32 && dst_space >= 16 {
            // SAFETY: `dst_space >= 16` gives 16 bytes of slack at `dst`;
            // `copy_16_bytes` is an overlap-tolerant load-then-store, and
            // `distance >= min_dist` guarantees the first `length` bytes — the
            // only ones relied upon — copy correctly even when `distance < 16`
            // lets the 16-byte windows overlap.
            unsafe { copy_16_bytes(dst, src) };
            while length > 16 {
                // SAFETY: `length > 16` bytes remain and the 16-byte slack keeps
                // `src + 16`/`dst + 16` within the buffer.
                unsafe {
                    src = src.add(16);
                    dst = dst.add(16);
                }
                length -= 16;
                // SAFETY: same 16-byte-slack invariant as the first copy.
                unsafe { copy_16_bytes(dst, src) };
            }
        } else {
            while dst != end {
                // SAFETY: `dst != end` keeps `dst` inside the `length`-byte match
                // region and `src` inside its earlier source region.
                unsafe {
                    *dst = *src;
                    dst = dst.add(1);
                    src = src.add(1);
                }
            }
        }

        // SAFETY: the macro compares `data_end`/`data` and `out_end`/`out_ptr`,
        // each a pair in one object.
        if unsafe { fast_inflate_should_continue!() } {
            continue;
        }
        break;
    }

    dc.set_out_ptr(out_ptr);
    dc.stream_view().set_bits(bits);
    dc.stream_view().set_left(left);
    dc.stream_view().set_chunk_ptr(data);
    1
}

// ufbx.c:3094-3101 `ufbxi_inflate_init_retain`
pub(crate) unsafe fn inflate_init_retain(retain: *mut InflateRetain) {
    // SAFETY: the caller provides writable `InflateRetain` storage large
    // enough for `InflateRetainImp` (layout asserted at ufbx.c:2028). Keep the
    // projection raw so initializing the cached tree does not assert an
    // exclusive Rust borrow over caller-owned retain storage.
    let ret_imp = retain.cast::<InflateRetainImp>();
    if !unsafe { (*ret_imp).initialized } {
        unsafe {
            init_static_huff(&raw mut (*ret_imp).static_trees, core::ptr::null());
            (*ret_imp).initialized = true;
        }
    }
}

// C comment (ufbx.c:3103-3130):
// TODO: Error codes should have a quick test if the destination buffer overflowed
// Returns actual number of decompressed bytes or negative error:
// -1: Bad compression method (ZLIB header)
// -2: Requires dictionary (ZLIB header)
// -3: Bad FCHECK (ZLIB header)
// -4: Bad NLEN (Uncompressed LEN != ~NLEN)
// -5: Uncompressed source overflow
// -6: Uncompressed destination overflow
// -7: Bad block type
// -8: Truncated checksum (deprecated, reported as -9)
// -9: Checksum mismatch
// -10: Literal destination overflow
// -11: Bad distance code or distance of (30..31)
// -12: Match out of bounds
// -13: Bad lit/length code
// -14: Codelen Huffman Overfull
// -15: Codelen Huffman Underfull
// -16: Litlen Huffman Overfull
// -17: Litlen Huffman Underfull
// -18: Repeat 16 overflow
// -19: Repeat 17 overflow
// -20: Repeat 18 overflow
// -21: Bad codelen code
// -22: Distance Huffman: Overfull
// -23: Distance Huffman: Underfull
// -28: Cancelled
// -29: Invalid ufbx_inflate_input.internal_fast_bits value
// -30: Bad window size (ZLIB header)
// ufbx.c:3131-3276 `ufbx_inflate` (public entry; C ABI shim lives in capi.rs)
pub(crate) unsafe fn inflate(
    dst: *mut c_void,
    dst_size: usize,
    input: *const InflateInput,
    retain: *mut InflateRetain,
) -> isize {
    let ret_imp = retain as *mut InflateRetainImp;

    // `input` is unconditionally dereferenced throughout this function (no
    // NULL check on the public entry point), so a local shared borrow is
    // sound (rule 4) in place of repeated `(*input).field` derefs. `ret_imp`
    // is left as a raw pointer: it aliases the `trees` pointer threaded
    // through the block loop below across iterations, so an exclusive
    // borrow here would not obviously stay sound for the whole function.
    // SAFETY: the public entry dereferences `input` unconditionally (never NULL
    // on this path), so a shared borrow over it is sound.
    let input = unsafe { &*input };

    let mut err: isize;
    // C: `ufbxi_deflate_context dc;` (uninitialized). Zero-init: C never reads
    // uninit fields except `stream.cancel_bits`, which upstream never writes —
    // it is read on cancellation (ufbx.c:2184) as stack garbage. Zero-init pins
    // that read to 0 (benign: cancellation is re-checked after every block).
    // PORT DIVERGENCE (ufbx.c:2184): because the block loop checks
    // `err < 0` before `dc.stream_view().cancelled()` (ufbx.c:3242-3245), C's garbage
    // bits can produce a data-dependent decode error (-10/-11/-12/-13) before
    // the -28 cancel return; pinned-0 bits make the mid-block cancellation
    // return code deterministic here, which may differ from a given C build.
    // No deterministic port can reproduce C's uninit read.
    // SAFETY: `DeflateContext` wraps `MaybeUninit<InnerDeflateContext>`, whose
    // all-zero bit pattern is a valid `MaybeUninit`, and the zero-init is the
    // intended C-parity initial state (see the note above).
    let dc: DeflateContext = unsafe { core::mem::zeroed() };
    // SAFETY: `dc.stream_view()` is `dc`'s own live bit-stream view, and `input`
    // is the borrow established above.
    unsafe { bit_stream_init(dc.stream_view(), input) };
    dc.set_out_begin(dst as *mut u8);
    dc.set_out_ptr(dst as *mut u8);
    // SAFETY: the caller's contract is that `dst` addresses `dst_size` writable
    // bytes, so `dst + dst_size` is its one-past-the-end pointer.
    dc.set_out_end(unsafe { (dst as *mut u8).add(dst_size) });
    if input.internal_fast_bits != 0 {
        dc.set_fast_bits(input.internal_fast_bits as u32);
        if dc.fast_bits() < 1 || dc.fast_bits() == 9 || dc.fast_bits() > 10 {
            return -29;
        }
    } else {
        // TODO: Profile this
        dc.set_fast_bits(if input.total_size > 2048 { 10 } else { 8 });
    }

    let mut bits = dc.stream_view().bits();
    let mut left = dc.stream_view().left();
    let mut data = dc.stream_view().chunk_ptr();

    // SAFETY: the locals mirror the stream's `bits`/`left`/`chunk_ptr`, and
    // `dc.stream_view()` is `dc`'s own live bit-stream view.
    unsafe { bit_refill(&mut bits, &mut left, &mut data, dc.stream_view()) };
    if dc.stream_view().cancelled() {
        return -28;
    }

    // Zlib header
    if !input.no_header {
        let cmf = (bits & 0xff) as usize;
        let flg = ((bits >> 8) as usize) & 0xff;
        bits >>= 16;
        left -= 16;

        if (cmf & 0xf) != 0x8 {
            return -1;
        }
        if (flg & 0x20) != 0 {
            return -2;
        }
        if (cmf << 8 | flg) % 31 != 0 {
            return -3;
        }
        if (cmf >> 4) > 7 {
            return -30;
        }
    }

    loop {
        // SAFETY: the locals mirror the stream's `bits`/`left`/`chunk_ptr`, and
        // `dc.stream_view()` is `dc`'s own live bit-stream view.
        unsafe { bit_refill(&mut bits, &mut left, &mut data, dc.stream_view()) };
        if dc.stream_view().cancelled() {
            return -28;
        }

        // Block header: [0:1] BFINAL [1:3] BTYPE
        let header = (bits as usize) & 0x7;
        bits >>= 3;
        left -= 3;

        let type_ = header >> 1;
        if type_ == 0 {
            // Round up to the next byte
            let align_bits = left & 0x7;
            bits >>= align_bits;
            left -= align_bits;

            let len = (bits & 0xffff) as usize;
            let nlen = ((bits >> 16) & 0xffff) as usize;
            if (len ^ nlen) != 0xffff {
                return -4;
            }
            // SAFETY: `out_end`/`out_ptr` are positions in the one output buffer,
            // so `offset_from` is in bounds.
            if unsafe { dc.out_end().offset_from(dc.out_ptr()) } < len as isize {
                return -6;
            }
            bits >>= 32;
            left -= 32;

            dc.stream_view().set_bits(bits);
            dc.stream_view().set_left(left);
            dc.stream_view().set_chunk_ptr(data);

            // Copy `len` bytes of literal data
            // SAFETY: `dc.out_ptr()` is the current output position with at least
            // `len` writable bytes (checked with the `-6` guard above), and
            // `dc.stream_view()` is `dc`'s own live bit-stream view.
            if unsafe { bit_copy_bytes(dc.out_ptr() as *mut c_void, dc.stream_view(), len) } == 0 {
                return -5;
            }

            // SAFETY: `len` bytes fit before `out_end` (the `-6` guard), so
            // advancing `out_ptr` by `len` stays within the output buffer.
            dc.set_out_ptr(unsafe { dc.out_ptr().add(len) });
        } else if type_ <= 2 {
            dc.stream_view().set_bits(bits);
            dc.stream_view().set_left(left);
            dc.stream_view().set_chunk_ptr(data);

            // C: `ufbxi_trees tree_data;` — zero-init (see `dc` note above;
            // `ufbxi_init_dynamic_huff` writes everything that is later read).
            // SAFETY: `Trees` is a POD of integer arrays, so an all-zero bit
            // pattern is a valid value.
            let mut tree_data: Trees = unsafe { core::mem::zeroed() }; // ufbxi_uninit
            let trees: *mut Trees; // ufbxi_uninit
            if type_ == 1 {
                // Static Huffman: Initialize the trees once and cache them in `retain`.
                // SAFETY: `ret_imp` is the caller's `retain` reinterpreted as
                // `InflateRetainImp` (layout static-asserted); field reads/writes
                // and the raw address of `static_trees` go through this live
                // pointer; `init_static_huff` accepts the `input` borrow.
                if !unsafe { (*ret_imp).initialized } {
                    unsafe {
                        init_static_huff(&raw mut (*ret_imp).static_trees, input);
                        (*ret_imp).initialized = true;
                    }
                }
                // SAFETY: `ret_imp` is live; `&raw mut` projects the cached tree
                // without manufacturing a temporary reference.
                trees = unsafe { &raw mut (*ret_imp).static_trees };
            } else {
                // Dynamic Huffman
                err = init_dynamic_huff(&dc, &mut tree_data);
                if err != 0 {
                    return err;
                }
                trees = &raw mut tree_data;
            }

            loop {
                // SAFETY: `trees` points either at the retain's `static_trees` or
                // the live local `tree_data`; `out_end`/`out_ptr` are positions in
                // the one output buffer, so `offset_from` is in bounds.
                let fast_viable = unsafe { (*trees).fast_bits } == HUFF_FAST_BITS
                    && unsafe { dc.out_end().offset_from(dc.out_ptr()) }
                        >= INFLATE_FAST_MIN_OUT as isize;

                // `ufbxi_inflate_block_fast()` needs a bit more upfront setup, see asserts on top of the function
                // SAFETY: `chunk_ptr` is in the current chunk; `chunk_yield` is
                // too EXCEPT in the C-parity wrapped `progress_interval` case
                // (progress cb + hint >= `usize::MAX`, see `bit_stream_init`),
                // where it is `ptr - 1` and may sit one below the chunk — the
                // same-allocation precondition of `offset_from` is inherited
                // from C's raw pointer subtraction, not independently
                // established here.
                if fast_viable
                    && unsafe {
                        dc.stream_view()
                            .chunk_yield()
                            .offset_from(dc.stream_view().chunk_ptr())
                    } >= INFLATE_FAST_MIN_IN as isize
                {
                    // SAFETY: `&dc` is the live context and `trees` the built trees.
                    err = unsafe { inflate_block_fast(&dc, trees) } as isize;
                } else {
                    // SAFETY: `&dc` is the live context and `trees` the built trees.
                    err = unsafe {
                        inflate_block_slow(&dc, trees, if fast_viable { 32 } else { usize::MAX })
                    } as isize;
                }

                if err < 0 {
                    return err;
                }

                // `ufbxi_inflate_block()` returns normally on cancel so check it here
                if dc.stream_view().cancelled() {
                    return -28;
                }

                if err == 0 {
                    break;
                }
            }
        } else {
            // 0b11 - reserved (error)
            return -7;
        }

        bits = dc.stream_view().bits();
        left = dc.stream_view().left();
        data = dc.stream_view().chunk_ptr();

        // BFINAL: End of stream
        if (header & 1) != 0 {
            break;
        }
    }

    // Check Adler-32
    {
        // Round up to the next byte
        let align_bits = left & 0x7;
        bits >>= align_bits;
        left -= align_bits;
        // SAFETY: the locals mirror the stream's `bits`/`left`/`chunk_ptr`, and
        // `dc.stream_view()` is `dc`'s own live bit-stream view.
        unsafe { bit_refill(&mut bits, &mut left, &mut data, dc.stream_view()) };
        if dc.stream_view().cancelled() {
            return -28;
        }

        if !input.no_checksum {
            let mut ref_ = bits as u32;
            ref_ = (ref_ >> 24) | ((ref_ >> 8) & 0xff00) | ((ref_ << 8) & 0xff0000) | (ref_ << 24);

            // SAFETY: `out_begin`/`out_ptr` bracket the initialized bytes
            // decoded so far in one buffer; the temporary slice spans exactly
            // that prefix and is not retained.
            let output = unsafe {
                crate::prelude::slice_from_ptr(
                    dc.out_begin(),
                    to_size(dc.out_ptr().offset_from(dc.out_begin())),
                )
            };
            let checksum = adler32(output);
            if ref_ != checksum {
                return -9;
            }
        }
    }

    // SAFETY: `out_ptr`/`out_begin` bracket the decoded output (same buffer), so
    // `offset_from` is in bounds.
    unsafe { dc.out_ptr().offset_from(dc.out_begin()) }
}

// ufbx.c:3278 `#endif // !defined(ufbx_inflate)` — END of the DEFLATE section.

#[cfg(test)]
mod tests {
    use super::adler32;

    fn scalar_adler32(data: &[u8]) -> u32 {
        let mut a = 1u64;
        let mut b = 0u64;
        for &byte in data {
            a = (a + byte as u64) % 65521;
            b = (b + a) % 65521;
        }
        ((b << 16) | a) as u32
    }

    #[test]
    fn adler32_known_values() {
        assert_eq!(adler32(b""), 0x00000001);
        assert_eq!(adler32(b"hello"), 0x062c0215);
        assert_eq!(adler32(b"Wikipedia"), 0x11e60398);
    }

    #[test]
    fn adler32_matches_scalar_across_alignment_and_chunks() {
        let data: Vec<u8> = (0..9000)
            .map(|i| ((i * 37 + i / 7 + 11) & 0xff) as u8)
            .collect();
        let lengths = [
            0usize, 1, 7, 15, 16, 17, 31, 32, 127, 128, 255, 256, 511, 512, 513, 1024, 4097, 8193,
        ];

        for offset in 0..16 {
            for &length in &lengths {
                let bytes = &data[offset..offset + length];
                assert_eq!(
                    adler32(bytes),
                    scalar_adler32(bytes),
                    "offset={offset} length={length}"
                );
            }
        }
    }
}
